### ISSUE TITLE
Integrate and refactor VSE Transform tools

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#100]
The add-on seems un-maintained while it does have some bugs and could use improvements. Looked into the code today and it's easy enough to start working on it. We could start by taking the move, rotate, scale and animation keying features and refining them. Maybe opacity control too.

That'd be one less add-on to download, while it's essential features for any editor.

**Comment by tin2tin** [comment]
Maybe team up with this guy who has been giving the tools an update? [https://github.com/doakey3/VSE_Transform_Tools](https://github.com/doakey3/VSE_Transform_Tools)

**Comment by NathanLovato** [comment]
Daniel updated the add-on and said he'll be maintaining his branch so let's close this for now.
