### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by doakey3** [GDquest/Blender-power-sequencer#107]
Since you're endorsing the VSE_Transform_Tools addon, how do you feel about removing `/operators/add_transform_effect.py`?

I'd like to change the way the render_to_web function works. I want to make it like an export function. When the user activates the operator, blender will ask for a filename (like it does when you try to save a .blend file). In this export menu, I can add some properties that would set the render format.

I started making a script that automatically generates the README based on elements in the code. [Here's a start of what I'm going for](https://github.com/doakey3/Readme_Experiments). Should I keep working on this or nah? I figure with so many functions and keyboard shortcuts to keep track of, it would be nice to have parts of the README autogenerated.

**Comment by NathanLovato** [comment]
for `add_transform_effect.py` we can change the name and shortcut, but it doesn't have the same purpose as the VSE transform one: it prepares pictures you just imported, resizing and making them transparent.

For render for the web, the point currently is with one keypress it sets all your render settings, names your file [and renders instantly]. There again I don't mind renaming it to something like "auto_render" or what-not but let's not remove it. It's a convenient shortcut when you make dozens of videos a month like I do.

Gotta start streaming now but for the generated docs, we started talking about it with @davcri. Now you've done the work it's good. I'll get back to you later but if possible I'd like to have more raw data we can re-pack differently because the docs will end up on gdquest.com (with inline video clips), using the hugo static generator

**Comment by NathanLovato** [comment]
**More about the docs**

What you did it is pretty good. However github is quite limiting in terms of layout and what we can have - e.g. we can add mp4 videos inline, we have to use gifs that even compressed are very heavy and cpu intensive.

Now all i'd need is the data... probably ideally as json. Like just the text, no formatting. This way it's easy to mix it with hand-written content and files with hugo's build system.

**Comment by NathanLovato** [comment]
*(I won't say it every time, but man thanks a lot for your help, I wouldn't have the time to do all that so it's incredible to have people around helping)*

**Comment by doakey3** [comment]
**Add transform effect**
OK, I think I'm going to remove the keyboard shortcut in VSE_Transform_Tools for adding a transform effect from the sequencer. It's kind of out of place since all the other shortcuts only have effect in the Image Preview window.

**Render for Web**
No problem. All I'm suggesting is the operator would seek out a filepath each time. All else would be the same. I just think that would be more consistent with Blender's other export functions

**Generating Docs**
So your main documentation will be on GDQuest.com. Can I make the README for the github page then? I could make a link to GDQuest.com show up near the top in big bold letters.

For the script, it's not too hard to do, but I'll need to make a few slight consistency changes to the operators (see below). 

For each operator...
1. Get the bl_idname
2. Get the bl_label
3. Get the bl_description. 
    - Here we're going to have to make them all be one-liners, even if the line ends up longer than 80 chars
4. Get the docstring inside the `"""`. 
    - We should either use Markdown or reStructeredText formatting in the docstring so it can easily be converted to html. We could include links to youtube or GIF links as well.
5. Get the shorctus
    - I think we need to add a property to all operators with multiple functions called "function". This will be just a string value that tells what particular function this keyboard shorcut will perform.

Exporting this out to a json should be easy enough.

**Comment by NathanLovato** [comment]
**Render for Web**
As long as I can bypass the file browser with some parameter no problem, even if the default shortcuts use the browser. It'll certainly be more intuitive for most users.

**Docs**

> Can I make the README for the github page then?

Sure, would love it :)
For the markup, can we go with markdown? RST is a bit more verbose and has often limited support in code editors, while there are excellent tools for md.
