### ISSUE TITLE
Change "Fade Strips" fade duration to a unit of time instead of frames

### ISSUE THREAD

**Issue by doakey3** [GDquest/Blender-power-sequencer#108]
Currently the "Fade Strips" operator has a "fade_length" property set to 12. This is probably because when editing a 24 fps video, 12 frames is half a second.

Could we change this to use 0.5 seconds by default and have it calculate where to put the keyframe based on the current scene FPS? This would allow for better consistency when editing videos of different frame rate.

**Comment by NathanLovato** [comment]
Definitely yes!

**Comment by doakey3** [comment]
[fixed](https://github.com/GDquest/Blender-power-sequencer/commit/16785fc8eb67a41dc539ac6273c9824f9b17ba66)
