### ISSUE TITLE
Make RippleDelete ripple from first strip in Timeline

### ISSUE THREAD

**Issue by doakey3** [GDquest/Blender-power-sequencer#109]
If I ripple_delete the first strip in the timeline, the strip is simply deleted with no subsequent rippling (concatenation) and a I get a message on the console that says "no strips to concatenate." 

It seems to me that the expected behavior would be for all remaining strips to be shifted leftward to fill in the space left over by the removed strip.

**Comment by NathanLovato** [comment]
Yeah because it uses the builtin remove gap at the moment - it needs a custom function to work. Planned for #98

**Comment by NathanLovato** [comment]
Needs #97 to fix
