### ISSUE TITLE
Concatenate Even When Modifier is Selected

### ISSUE THREAD

**Issue by doakey3** [GDquest/Blender-power-sequencer#110]
I'd like to make a slight adjustment to the concatenation function. Currently, if a user selects a modfier strip and attempts concatenation, they get a response "no strips to concatenate". 

I think it wouldn't be too difficult to recursively check strip_input1 & strip_input2 until a strip is found without any inputs and concatenate from there. I was stuck for a few minutes thinking I had screwed up a keyboard shortcut or something when really I just needed to select the base strip before concatenating.

**Comment by NathanLovato** [comment]
Sure!
