### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by mond-cz** [GDquest/Blender-power-sequencer#112]
I just post an issue on blenders bug tracker, because I hit button you use in user pref for addon.
Can you move this  button out or redirect the URL to relevant address for bugs?
Thank you

https://developer.blender.org/T54282
Note: I just spent hours searching what cause disfunction of smoke sim. Strangely it was this addon. Reason why I post the bug was messed versioning. I used 0.9.0 from January 12 (thats what updater said). I thought its last version. I tried to check for update with your addon's pref, but for some SSL reason I'm not able to check it. On GIT I saw last version 0.9.0 too, so I got a feeling I'm using the last version. Later on I noticed some changes January 30 so I downloaded and install this newer version and smoke sim works. So ignore the post on bug tracker. 
Anyway some closer versioning would be helpful, or what is the best way to check if I use last version - a date?
(I just checked init.py file.)

**Comment by NathanLovato** [comment]
The report a bug button comes from Blender, not from the addon. It's for add-ons that are officially part of Blender.

I'm closing this issue, let's discuss on the other bug report

**Comment by doakey3** [comment]
I couldn't replicate the quick-smoke issue on either my Arch Linux machine or Windows 7. I'll check OSX using my friend's Macbook later today.

**Comment by doakey3** [comment]
I added a line called "tracker_url" to the bl_info part of the addon. This will make it so that clicking the "report a bug" button will link to the Power-Sequencer issues page instead of the official blender bug tracker.

**Comment by NathanLovato** [comment]
The author said updating from beta 1 solved the issue so it's okay

On March 12, 2018 11:58:20 PM GMT+09:00, Daniel Oakey <notifications@github.com> wrote:
>I couldn't replicate the quick-smoke issue on either my Arch Linux
>machine or Windows 7. I'll check OSX using my friend's Macbook later
>today.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/GDquest/Blender-power-sequencer/issues/112#issuecomment-372339410

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NathanLovato** [comment]
Thanks, didn't know we could use this :)

On March 13, 2018 2:14:43 AM GMT+09:00, Daniel Oakey <notifications@github.com> wrote:
>I added a line called "tracker_url" to the bl_info part of the addon.
>This will make it so that clicking the "report a bug" button will link
>to the Power-Sequencer issues page instead of the official blender bug
>tracker.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/GDquest/Blender-power-sequencer/issues/112#issuecomment-372389656

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mond-cz** [comment]
Yeah, sorry I didn't know that.
Severin (blender dev) did some changes to protect this user (like my) action :)
https://developer.blender.org/rB41b38c5f75b371e3897685fd9a4cb953a4aa65ff
