### ISSUE TITLE
Check for Update

### ISSUE THREAD

**Issue by mond-cz** [GDquest/Blender-power-sequencer#113]
Can you recognise a reason for disfunction?
(the first screen is from older version, second from today download, but I wasn't check update even with older one). Isn't that related to "fixed" security issue that block some functionality now?
https://www.blendernation.com/2018/01/13/vulnerabilities-blender-whats-impact/
Thank you for help. 

![screen shot 2018-03-09 at 20 07 03](https://user-images.githubusercontent.com/649050/37226495-6c61d358-23da-11e8-8a88-9de5bb25e4cb.png)
![screen shot 2018-03-09 at 20 40 53](https://user-images.githubusercontent.com/649050/37226496-6c7d63ca-23da-11e8-952d-31a3a6d61212.png)

**Comment by NathanLovato** [comment]
If you didn't update Blender, nothing should've changed when it comes to server communication? 

I've never had this issue before even with the latest Blender. The updater part is made by another developer and the code is quite complex. I wouldn't even know where to look right now.

If you have trouble with this feature, you can always update the add-on manually like you update any Blender add-on. Let's ping @TheDuckCow, the tool's author, and see if he knows why this happens

**Comment by doakey3** [comment]
I'm a little unclear about what @mond-cz means about there being a dysfunction here. Can you describe the problem a little more?

**Comment by TheDuckCow** [comment]
Please see [this thread here](https://github.com/CGCookie/blender-addon-updater/issues/39) - this is unfortunately a known issue introduced on Feb 22nd, due to GitHub being more strict in its SSL api connections, an issue that happens to only affect OSX builds (2.79 and below).

This is not an issue that realistically can be resolved; It is very unlikely GitHub will make their api connections more lax again, and existing builds of blender simply don't have the right ssl libraries included (again, only for OSX as it turns out; Windows and Linux are fine).

**Comment by NathanLovato** [comment]
Thanks much Patrick. I'm sorry it can't be fixed mond-cz. Maybe with Blender 2.8 then? Although there's still some way to go. You will likely have to update manually then.

**Comment by TheDuckCow** [comment]
The good news is the SSL certs in blender 2.8 seem to comply with what GitHub wants, so any updates required to make 2.8 work are more to do with meeting the updated setup of the python api (and the change in available handlers in particular).

In the meantime, indeed manual updating will have to be the way to go for those encountering this error.

**Comment by mond-cz** [comment]
Thank you guys for your report and attention :)

I can do it manually of course, but I use bunch of addons (as many of us). Usually simply copied for a new version of blender, so this auto-update seems to every handy in general, I hope it become standard feature. Specially in case with smoke sim I post earlier. You can imagine the long way to find a reason for that. 

For SSL reason I can't even connect to the Blender Cloud with daily builds (luckily it works with official version, that I can confirm with this auto-updater). 

I'm not complaining here :) I understood the reason. I'm just looking for shining future (for OSX too) :)
Thank you for your time.
