### ISSUE TITLE
How to handle animations and transitions?

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#119]
It's common to want to reuse preset animations or to need to embed small projects into another. E.g. for a title animation, a social network widget that would pop on to the screen...

## The issues

You can append a scene dynamically using a scene strip,

1.  but it takes time to cache and render.
2. It takes quite a few steps to load and setup image strips to apply a custom transition (wipe in any direction, etc.) while they generally come as one-click presets in other editing programs.
3. It's a little hard and cumbersome to copy and paste animation from one strip to another, and especially from one project to another in the sequence editor. Yet in animation, you often use a lot of repetition, so you'll often want to reuse, offset, scale animation tracks.

## Solutions

Some kind of UI to manage presets/quickly import and reload reusable footage and scenes from a few folders could be a solution. Something a bit like Pitiwazou's Asset Management add-on:

![image](https://user-images.githubusercontent.com/12694995/38005664-9ae595f6-327c-11e8-89c0-6e1f35a63062.png)

It'd certainly be quite a bit of work but what do you think? Would anyone else be interested in this?

*Opening this discussion right now so I don't forget. I have this issue often*

**Comment by 3pointedit** [comment]
It night depend on the thumbnail image, as it's often not clear what happens later in the animation. As long as the user could scrub or set the thumbnail it should be handy. Also it would be nice to interpret the incoming scene to see if it should be set to Blend type Alpha over or similar? Would you drag and drop it from the browser window to the timeline?

**Comment by NathanLovato** [comment]
If we have a short video or gif for the thumbnail it might be possible to play it back on hover.
It's not going to work with the file browser if it happens though. And to be fair I don't have time to do it. Blender 2.8's asset management may help to solve the issue.

**Comment by NathanLovato** [comment]
After looking into the issue, I feel it's out of scope for the add-on. You get to the point where it's probably better to use another program, or you'll need some serious investment to get the workflow up in blender.
