### ISSUE TITLE
Cannot go back in time precisely when playback speed in different than normal

### ISSUE THREAD

**Issue by Acvarium** [GDquest/Blender-power-sequencer#120]
If you changed the playback speed with your drop-down menu, the Play in Reverse will not work

**Comment by NathanLovato** [comment]
Fixed although playing backwards will only go at 1x. There's no reliable way to track if you're playing forward or backwards in Blender and I've always got this bug where playing backwards can work for faster etc. but on double it hangs and on triple speed it moves in the wrong direction. It'll have to do for now.
Thanks for the report!
