### ISSUE TITLE
Install error on the latest version

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#125]
Reporting on behalf of @guilhermehto:

In `register_keymap.py` the try/except block to get the `keymap.json` file causes an error on his system (Windows):

![image](https://user-images.githubusercontent.com/12694995/40400347-acd5c2e6-5e7c-11e8-8869-717037687f6a.png)

Seems to be due to the `addon_module_name` method (renaming it to `get_addon_module_name` in a second).

```py
    try:
        with open(keymap_filepath, 'r') as f:
            keymap_data = json.load(f)
    except FileNotFoundError:
        addon_name = addon_module_name()
        preferences = bpy.context.user_preferences.addons[addon_name].preferences # the issue is here
```

@guilhermehto can you show me where you placed the add-on, how you symlinked it in the blender add-ons folder please?

@doakey3 could you check this? Maybe you have an idea why this happens?

Last issue to solve before pushing 1.0!

**Comment by doakey3** [comment]
I recommend we do away with the keymap.json stuff. It was a nice idea, but overly complicated and the different keymaps idea just didn't take off. Plus, I'm fast approaching a time where I won't have time to maintain any code. I'd be willing to help revert this thing back to something workable and simple.

**Comment by guilhermehto** [comment]
Here's what I did:

Cloned the repo to a working folder on my system.

Created a symlink using:

```sh
$ mklink /d "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\power-sequencer" "C:\!GDQuest\Blender-power-sequencer"
```

Opened blender -> user prefs -> Activate power sequencer

This error only occurs when I try to use the addon by using/cloning the master. If I use the beta, everything works fine.

**Comment by NathanLovato** [comment]
@guilhermehto Okay your symlink is wrong, that's why you have the issue. The arguments `MKLINK Link Target` mean `mklink folder_name target_path` -> you named your symlinked folder `C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\power-sequencer`, and the command line or Blender doesn't like the space and maybe the \ as well.

@doakey3 I think it's good! I haven't had a single issue with it since you added support for properties. Don't worry about reverting it. I think it's more that there are few Blender VSE users overall, and people who edit videos are likely not experienced developers so they can't contribute code. 

I can maintain or revert it myself when you start working. I've got two tutorial videos ready by the way. Are you okay if I publish them along with the two you made?

I asked some experienced developers how I could motivate new devs to contribute and grow the community a little bit. Beyond the community aspect, one recommended to look at LateX's bounty system.

Thank you very much again for your help, I greatly appreciate it! Best of luck in your new job and in what's certainly going to be a busy life :)

Regarding usage and contributions, another thing is the Blender VSE itself really needs a maintainer and has some core limitations that make it unusable for a lot of people: limited performances so you can only edit "simple" videos + one framerate makes it a little too technical for a lot of people. Larger professional packages tend to just work out of the box now - I tried DavinciResolve 15 in parallel for live footage and even proxies are generated automatically, asynchronously when you're not using playback etc. And only on the chunks of video you add to the timeline.

@guilhermehto You can find your add-ons folder in `~/appdata/Blender foundation/2.79/addons` iirc. Can you check that this works?

**Comment by guilhermehto** [comment]
I'll try using the addons folder at appdata and post the result. 
About the symlink, I'm pretty sure you can use an absolute path on it, but I'll do as you said. Nonetheless, when I wasn't using a symlink the problem was still the same.

**Comment by doakey3** [comment]
I've gotten rid of the complex code and replaced it with something similar to how it's done on [Blender's Addon Tutorial page](https://docs.blender.org/api/blender_python_api_2_65_5/info_tutorial_addon.html#keymap). You can check the code in my [temporary branch](https://github.com/doakey3/Blender-power-sequencer) (and please do make sure I got the shortcuts right). I'll write a new readme_generator.py tomorrow.

**Comment by doakey3** [comment]
> Don't worry about reverting it

Oh, already did. It's in a different branch though, so you can see how you like it and use it if you want.

> Are you okay if I publish them along with the two you made?

Yup fine by me. I hope people find them useful.

**Comment by NathanLovato** [comment]
@guilhermehto Daniel removed the code that caused the issue :)
I'll close as it should be okay now. Please tell me if you have any problem
