### ISSUE TITLE
Check for each video's framerate reliably before import

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#126]
Importing videos with different framerate in batch:

1. will mess up your project
2. can crash blender

Add code to:

- [ ] Check a video's framerate with ffprobe
- [ ] Ensure all newly found videos have the same framerate **before importing**
- [ ] Compare the footage's framerate against the project.
  - If the blend file is fresh, change the framerate and tell the user
  - If it's a new scene, allow the framerate to change but warn the user if it's different from previous scenes

The user will need ffprobe, but it should come along with ffmpeg that they'll need to make the most out of the add-on. Wrote a quick function to get started
Related to #48 as the tool could also offer to transcode videos before importing them

```py
def get_video_framerate(video_path):
    """
    Runs ffprobe with the video_path and returns fps, fps_base, a tuple of int, float
    That's the video's framerate in Blender's format
    If ffprobe isn't installed, returns None
    """
    status, _ = subprocess.getstatusoutput('ffprobe')
    if status != 0:
        return None

    def calculate_fps_from_string(input_string: str):

    command_args_list = "ffprobe -loglevel quiet -print_format json -show_streams -select_streams v {!s}".format(video_path).split()
    ffprobe_output = subprocess.check_output(command_args_list)
    video_info_dict = json.loads(ffprobe_output)

    fps_string_base, fps_string_divisor = video_info_dict['r_frame_rate'].split('/')
    return int(fps_string_base / 1000), float(fps_string_divisor / 1000)
```

**Comment by davcri** [comment]
This seems like an important issue to improve UX: if you are just starting with Blender and BPS, then you can get really confused by importing videos and see them playing at different speeds.

**Comment by NathanLovato** [comment]
Looking back, I think it's beyond the scope of PS. People will also need an external program like ffprobe to use a feature like this one - I don't think we have access to the footage's framerate in Blender.
