### ISSUE TITLE
mouse_trim.py UnboundLocalError: 'frame' referenced before assignment

### ISSUE THREAD

**Issue by guilhermehto** [GDquest/Blender-power-sequencer#131]
### _First step:_
- Create/find an empty area between 2 strips
- Ctrl + Click on the empty area to concatenate the strips
### _Second Step:_
- Cut a strip using K
- Ctrl + Click to Ripple Delete from the Cursor's position to mouse position
- You'll get the error

```
Traceback (most recent call last):
  File "C:\Users\htogu\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\mouse_trim.py", line 87, in invoke
    bpy.context.scene.frame_current = frame
UnboundLocalError: local variable 'frame' referenced before assignment

location: <unknown location>:-1
```

The Ripple Delete works fine before using the Ctrl + Click to concatenate strips.

## But here's where it gets weird:
If I repeat these steps and the end of the timeline, everything keeps working fine. Here's an example of where it would be fine on the project that I was testing:
![2018-06-05 15_33_18-window](https://user-images.githubusercontent.com/20494771/40995669-15a66376-68d6-11e8-8efa-b48bd5795ebe.png)

However, If I repeat these steps on the beginning, the error will occur:

![2018-06-05 15_33_00-window](https://user-images.githubusercontent.com/20494771/40995676-1d413bec-68d6-11e8-8117-4d19aeb9c276.png)

I have the latest version from Master running.

_ps.: I might have not used the correct terminology, hence why I'm also giving the shortcuts_

**Comment by NathanLovato** [comment]
That's not linked to other operators. When you have an issue like that you can start with just the backtrace, often it'll be enough to fix the bug. In this case
```
  File "C:\Users\htogu\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\mouse_trim.py", line 87, in invoke
    bpy.context.scene.frame_current = frame
UnboundLocalError: local variable 'frame' referenced before assignment
```
It's just a variable that was in the wrong scope so sometimes it wasn't initialized. Should be fixed with the latest commit
