### ISSUE TITLE
Render with proxy files with BPSRender

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/blender-power-sequencer#138]
## Problem

Rendering videos in blender takes a long time. Sometimes you may want to render a sample at a smaller resolution to hand out to a client or preview the video in a different player, on a different device.

## Solution

**EDIT**: only apply the change to a local copy of the blender file, for rendering, using the multithreaded render script! This way no risk to mess up your original work file

If the user renders with 50% proxies, it should auto render at 50% of the resolution. Same idea with 25% proxies.

------------------

_Old issue comment_

As you need proxies to work and they're generally smaller than the source footage, they're a lot faster to render.

This feature is about having a script that swaps the `filepath` on all selected strips with proxies it finds in the `BL_proxy` folder. It's easy enough to swap the paths:

```py
def get_proxy_filepath(path):
    head, tail = os.path.split(path)
    return os.path.join(head, "BL_proxy", tail, "proxy_25.avi")

def get_video_filepath_from_proxy(path):
    filepath = os.path.split(path)[0]
    filepath, filename = os.path.split(filepath)
    dirpath = os.path.split(filepath)[0]
    return os.path.join(dirpath, filename)
```

But there are a few issues:

- In the addon the convention is to use 25% proxies because even with 50% proxies video playback can be slow, due to Blender's playback engine being old and running only one one CPU core
- By default video strips have no proxy settings in Blender. If people set them up in their project (per strip) I don't know how to 
- If it has a bug, the tool can severely mess up your project, so it should have tests or something.
- swapping the path on many sequences takes time so it should have progress report

I'm using bits of code like these manually to render some videos quickly at times and it's often useful. So opening the discussion here to get some feedback on it.

**Comment by sudopluto** [comment]
this exists, I feel we could make our own version of this and add it to the scripts
https://github.com/sciactive/pulverize

**Comment by NathanLovato** [comment]
Ah good! Pulverize.py is pretty short so we could indeed bring it in, clean it up a tiny bit and work from this. Thanks for the suggestion!

**Comment by NathanLovato** [comment]
It's also possible to spawn the process from a blender operator, and I saw someone use blender's header progress bar with a script, it'd be nice if we could use this as well (although not a priority)
