### ISSUE TITLE
add ood to the proxy script

### ISSUE THREAD

**Issue by sudopluto** [GDquest/Blender-power-sequencer#139]
i think a good thing to do before starting new features to the proxy script is to make it use clases and objects rather than conditional logic. 

If we can make a video-proxy-obj, then adding md5 checking and such would be easier. the code would also be more readable.

I will be starting this soon.

**Comment by NathanLovato** [comment]
Thank you very much! Your help is super appreciated here.

**Comment by sudopluto** [comment]
started pull request here: https://github.com/GDquest/Blender-power-sequencer/pull/142

could use some testing / a review

**Comment by NathanLovato** [comment]
Fixed with #142
