### ISSUE TITLE
Make a video overview of the add-on

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#14]
Show the main features and how they help to work faster than with Blender's builtin tools.

**Comment by davcri** [comment]
It would be really nice in order to "get started" easy with this plugin!

Can I help in some way ?

**Comment by NathanLovato** [comment]
Thank you!
Before we get to this task, the add-on needs some docs and a proper github landing page. The community said these 2 were more important than tutorials. If you want to help with any of the tasks, you're welcome!
