### ISSUE TITLE
Refactor render_video_multithreaded.py

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#143]
From the last commit on the `multithreaded-render-script` branch:

> Needs refactoring AND testing! I fixed what I could and started renaming variables but the original
> script didn't run here, and for now the concatenation command doesn't output
> anything (but doesn't trigger an error, and copying and running it manually in the shell works)
> 
> TODO: use clear variable names, split functions that generate data (make them
> pure) from the parts of the script that run commands

**Comment by NathanLovato** [comment]
@sudopluto said he'll be taking a shot at it in #147

**Comment by NathanLovato** [comment]
@sudopluto Thanks :)
Here's a test project, with footage and proxies prepared for you, that you can use to test the multithreaded renderer. Please tell me if I can help with anything else!
[power-sequencer-tester.zip](https://github.com/GDquest/Blender-power-sequencer/files/2153386/power-sequencer-tester.zip)

**Comment by sudopluto** [comment]
Thanks for the test.zip, I'll start working on this soon hopefully. work will be done here: https://github.com/sudopluto/blender-power-sequencer/tree/multithreaded-render-script

**Comment by sudopluto** [comment]
just looked at the script and the upstream, going to take some notes below

- there is already a pull request on upstream for the audio cuts: https://github.com/sciactive/pulverize/pull/15 (wow its really new), might be worth taking a look
- there doesn't seem much to actually refactor besides just cleaning it up a bit
- as far as I can tell, there is no memory bound to the default amount of workers. this should be fixed.
- I'm still having trouble testing out the script, do I need to launch it from within blender somehow?
     - getting an import error: bpy not found
- should we notify upstream? them seem to be active

**Comment by sudopluto** [comment]
ok finally got around to setting up blender, and started cracking at this here: https://github.com/sudopluto/blender-power-sequencer/tree/refactor-multithread

- whats done so far:
    - removed logging
    - removed second file, that gets generated and deleted by the main script
    - finally got around to paths (this was really wonky on my linux machine)
    - switched over to pools instead of manually tracking processes

some stuff for the near future when the refactor is done

- some notes / concerns
    - while path is working fine now, I don't like my solution. I just take the dir of the .blend file, and 
    create a new dir called render and dump the file there
        - if there is a better way / one that aligns better with the blender dialogue, I would like to 
        implement that
    - while I can grab progress from blender about rendering, it deadlocks the program, because of this:
    https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait
        - how much progress notification do we need? i can try to trim the output, but one idea is to make
        it so that progress is done by chunk, not by chunk
    - mem bound is non-existant. we can
        - import a lib 
        - write platform dependent code
        - trust the user not to overload on workers

**Comment by sudopluto** [comment]
also should I consider the separate audio mixdown as part of the refactor, or just implement the concat
the way it is currently?

**Comment by NathanLovato** [comment]
Thanks for your work!
First, I'd like us to keep logging and dry run. We don't have any other way to debug the script for now. And it's a command-line program, it should still work outside Blender.

> I just take the dir of the .blend file, and create a new dir called render and dump the file there
> if there is a better way/one that aligns better with the blender dialogue, I would like to implement that

There is an alternate option using Blender's API: you have a `bpy.path` module to get the path to render to https://docs.blender.org/api/current/bpy.path.html
You can also get the render path relative to the .blend file, in blender's format, in `bpy.scenes[SCENE_NAME].render.filepath`. You can loop over scenes, or access the active scene in the .blend file with `bpy.context.scene`. 

Now by default, it's likely going to point to the user's TMP folder, and it can be hard to find. I don't know what's best, but I personally prefer for this render program to output to the project folder as:

1. That's what the add-on encourages. Blender works best this way in my opinion as you don't have a good system to reference files from a server, your video library, etc.
2. We render chunks that the user may want to keep, or to delete later, or to concatenate manually. I'd like to have them around to know where to find them

> how much progress notification do we need? 

I think an update every second or so would be nice. There's some way to get the rendered frames as [RenderController](https://github.com/Isti115/BlenderRenderController) had it. I guess you could read the output strings from Blender? It prints rendered frames to the console.

> mem bound is non-existant

I don't have experience writing for multiple cores. Trusting you on this one. Adding a cross-platform lib is fine as long as it's not huge. Don't make it too hard for yourself.

>  should I consider the separate audio mixdown as part of the refactor

The author of the PR on pulverize offered to make a PR here. There's a separate issue for it #148 
I guess for now you can keep the current concatenate method.

**Comment by sudopluto** [comment]
Sorry if I wasn't clear, now that I have read over my comment it is a bit messy, was writing it just before I slept.

So the the current setup is 
```
|> project folder/
    |> project.blend
    |> render/
        |> render.mp4
        |> render_chunks/
            |> (all the chunks)
```

So the final render and the chunks are all in the the project folder, although I don't know enough about
blender scenes to really comment on that part.

--------

so the problem I had with progress is that Popen.wait() would deadlock, because of an overload of 
output. I can try later using Popen.communicate(), but the more I think about it, the more that feature
is outside the scope of a refactor, and I should handle it separately when the basics are done.

-------

the mem bound issue is kinda a non issue, basically if the user supplies the number of workers, we
should give a warning to not overload their system

-------

I'll just tack on the audio  cuts to the post-refactor todo list.

-------

post refactor:
- audio cuts
- progress
- logging / dry run

**Comment by NathanLovato** [comment]
All good! Keep it simple for this one, and there are other issues open for adding features later.

> basically if the user supplies the number of workers, we should give a warning to not overload their system

Ah okay! Isn't `os.cpu_count()` reliable there? From the docs:

```
Return the number of CPUs in the system.

This number is not equivalent to the number of CPUs the current process can use. The number of usable CPUs can be obtained with len(os.sched_getaffinity(0))
```

**Comment by sudopluto** [comment]
while each blender instance uses ~400MiB on my system, other projects (render controller?), have reported ram usage of 1.6 GiB and greater. There could be an edge case where someone has many
cpu cores, but not a lot of ram. Therefore, when they run the program, the ram is maxed out and the os becomes unresponsive.

**Comment by NathanLovato** [comment]
Ah got it! That's fine, we can leave that up to the user.

**Comment by sudopluto** [comment]
ok, a very alpha refactor is up via https://github.com/GDquest/Blender-power-sequencer/pull/158

**Comment by NathanLovato** [comment]
Calling this a day! Let's open new issues for more
