### ISSUE TITLE
ffmpeg_build_proxies stay stuck in some situations

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#146]
Probably my bad, I may have broken it with the merge, or not tested it enough. Gonna fix it tonight

**Comment by sudopluto** [comment]
have you tried it with the old script to see if that version gets stuck too? do you have a copy of the folder that results in the hang?

**Comment by NathanLovato** [comment]
Yeah don't worry, I broke it, I'll fix it. Just haven't had time yesterday night
