### ISSUE TITLE
multithreaded renderer: cuts in the audio after concatenation

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#148]
FFmpeg's concatenate feature works great on video but adds an audio cut at every junction.

## To fix this

- [ ] render video chunks without audio (may encode slightly faster, we won't use the audio anyway)
- [ ] render audio mixdown from Blender
- [ ] concatenate chunks and add the audio from the mixdown

You can add the audio to the video concatenation like
```shell
ffmpeg -f concat -i list.txt -i audio.wav -c:v copy -map 0:v:0 -map 1:a:0 -c:a aac -b:a 192k out.mp4
```

## Extra 

- [ ]  Add a cmd line option to render the mixdown only, e.g. if you already rendered the chunks
- [ ] Leave the option to skip the mixdown and issue a warning

**Comment by sudopluto** [comment]
please check if the refactor solves this https://github.com/GDquest/Blender-power-sequencer/pull/158

**Comment by NathanLovato** [comment]
The code seems in place, but it doesn't run on my system. I'll try to get this to work
