### ISSUE TITLE
multithreaded renderer cannot be interrupted

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#149]
Once the render started, the only way to stop rendering is to kill the process.

**Comment by sudopluto** [comment]
might be partially solved by https://github.com/GDquest/Blender-power-sequencer/pull/158, might need a nicer error message

**Comment by NathanLovato** [comment]
Still can't be interrupted here, the only way to stop the processes is to kill the shell on windows 10. Not a big deal atm but it'll need a fix eventually

**Comment by sudopluto** [comment]
I don't know how to test this on my machine since keyboard interrupt (ctl-c) is working just fine. 
In order to stop cleanly my gut instinct would be to override the keyboard interrupt in order to delete the partially rendered parts.

I could start googling this, it seems to be a common issue, with blogposts like this popping up on a first
search: https://jreese.sh/blog/python-multiprocessing-keyboardinterrupt

**Comment by sudopluto** [comment]
Also I have no idea how one would pause a render from the terminal. On my machine, I would probably 
suspend the process from the os side (ctl-z), but I have no idea if that exists on windows.

**Comment by NathanLovato** [comment]
Not on Windows, you've got to write a shell script, or go to the task manager -> kill the shell ^^

**Comment by NathanLovato** [comment]
From this blog post, it seems simple enough! So you wait in a loop either for the process to terminate or listen to keyboard interrupts? Simpler than I expected :)

**Comment by NathanLovato** [comment]
Hey @sudopluto , do you want to tackle this one, or should I do it? It's the last bug and dev task left to release 1.1.

**Comment by sudopluto** [comment]
I don't have a windows machine, so it's kind of hard for me to test this one. I can help doing research on possible solution, but I don't think I can do this one.

**Comment by NathanLovato** [comment]
No problem, thanks for your article. I'll work on it :)
I looked at the multiprocessing docs and tried a few things... it's a common problem indeed, and it can be a little finicky. I tried a few approaches without success. One worked well but auto-terminated after a timeout. I think there's something to do with map_async and the AsyncResult object it returns: it's the only one that lets you poll the pool's status.
Anyway, on windows, you have to call Pool.terminate() to stop it (or manually find and kill the processes). But a few alternatives I tried didn't work with PowerShell - it didn't want to respond to kbd input.

**Comment by NathanLovato** [comment]
Razvan offered to look into the issue. Some comments from him:
```
from the very little I read it might be due to the fact that the processes aren't spawned within a parent (the bash shell), they're detached and that introduces some potential problems if you want to terminate them early
I read that there's a way to group the processes together and attach them to the parent shell and if the parent receives an interrupt then the event gets bubbled in the group as well
```

**Comment by NathanLovato** [comment]
Razvan fixed the issue, he'll put a PR up after some refactoring :)
