### ISSUE TITLE
Preview to selection (ctrl alt P)

### ISSUE THREAD

**Issue by Benito1111** [GDquest/Blender-power-sequencer#150]
when I uncheck the ALT box, it works (ctrl P).
Do you have an idea why?

**Comment by NathanLovato** [comment]
Can you check your input settings? If `power_sequencer.preview_to_selection` is set to ctrl alt P like on this picture it has something to do with your system/keyboard.

![blender_2018-07-03_09-04-08](https://user-images.githubusercontent.com/12694995/42191857-2e78ac6c-7ea0-11e8-8860-0e072b229ec0.png)

**Comment by NathanLovato** [comment]
It doesn't seem to be linked to the add-on so I'll close the issue for now. If you need anything else please reopen it, and tell us more!
