### ISSUE TITLE
Mouse Trim Controls are Ctrl-Alt-RMB and Shift-Ctrl-Alt-RMB instead of Ctrl-RMB & Shift-Ctrl-RMB by default

### ISSUE THREAD

**Issue by eplipswich** [GDquest/Blender-power-sequencer#153]
Something to note of.

**Comment by eplipswich** [comment]
Yeah, it's the latest version from the releases. Addon is up to date too:

![image](https://user-images.githubusercontent.com/37729199/42297992-e807d28e-8035-11e8-95ca-3527b4179d09.png)

Yet, it shows "Shift Ctrl Alt Select Mouse" and "Ctrl Alt Select Mouse" under "Mouse Trim Strips" for some reason:

![image](https://user-images.githubusercontent.com/37729199/42298037-2c73a8bc-8036-11e8-8db8-f9fee1b84b64.png)

**Comment by NathanLovato** [comment]
Actually my bad, the shortcuts were correct, but the readme was outdated! Fixed.
