### ISSUE TITLE
Suggestion: Make Mouse Cursor Snap to a Cut/Marker/Playhead when Cutting

### ISSUE THREAD

**Issue by eplipswich** [GDquest/Blender-power-sequencer#154]
Would be cool to have this function, which also exists when using the Razor tool in Resolve. This will especially be handy when Mouse Cutting a strip.

**Comment by eplipswich** [comment]
You could change Ctrl to Alt for Mouse Trim and Mouse Cut controls, then change Mouse Toggle Mute to Alt MMB or Alt RMB and Trim to Surrounding Cuts to Shift-Alt MMB or Shift Alt RMB.

**Comment by NathanLovato** [comment]
It's harder than that:

- Middle mouse doesn't work for people working with styluses and two-button mouses. Mouse toggle mute isn't super important but `Trim to Surrounding Cuts` is one of the biggest time savers in the add-on
- Alt [Shift] Select Mouse is already used by default, and the feature is very useful as well (toggle select handles)

Will have to think about this.

**Comment by NathanLovato** [comment]
I forgot about this issue but I added this recently. It's available in the master branch of this repository (the blender 2.80 version of the add-on, coming out after Blender 2.80)
