### ISSUE TITLE
Suggestion: Remove quick save shortcut by default?

### ISSUE THREAD

**Issue by FraYoshi** [GDquest/Blender-power-sequencer#155]
I don't think this function to be that much related to the sequencer, I mean.. Someone could find useful the confirmation.. u.u it should be something toggleable.

**Comment by NathanLovato** [comment]
Yup, it's one of the oldest bits of code in the add-on, should def. move it to some other script or make it inactive by default

**Comment by NathanLovato** [comment]
As the feature is sequencer-only, the issue doesn't seem to impact you personally, and nobody else brought it up so far, closing for now.
