### ISSUE TITLE
Merge register_shortcuts.py with shortcuts_docs.json

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#157]
I'll take care of this. 
But @doakey3 could you just confirm the "function" param you added to the shortcuts isn't used anywhere? I can't find any code that uses it, including in the `make_readme.py`. I see you added this property to a number of operators but it's never used. Talking about this:

![emacs_2018-07-05_19-16-55](https://user-images.githubusercontent.com/12694995/42317722-feb6feb8-8087-11e8-86f0-5a78fb6b7b2b.png)

![emacs_2018-07-05_19-16-07](https://user-images.githubusercontent.com/12694995/42317692-e9869904-8087-11e8-8132-b7a056940e5c.png)

Just to be sure I can remove them all.

**Comment by NathanLovato** [comment]
Thanks :) !

**Comment by NathanLovato** [comment]
Did some preliminary work in 0160729a3b6dca4a2693d0c15b5ac160e2fe85a4

To do:

- [ ] Serialize register_shortcuts.py as JSON
- [ ] Merge descriptions from shortcuts_docs.json
- [ ] Create functions to convert JSON back to `KeyMapItem`

The idea to have shortcuts as data was great imo, and so is having everything in one place to register shortcuts and generate docs. Only the data format made it harder to use than it needed to be.

**Comment by razcore-art** [comment]
sorry, completely missed the low priority label so I worked on this a bit with a proposal in #274. Let me know if you guy think it's a good idea or not and we can discuss it
