### ISSUE TITLE
A way to visualize both ends of a cut as you slide strips?

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#172]
One of the features I miss the most editing in Blender's VSE is the ability to visualize where cuts end up when:

- you move a handle
- you slide a strip
- you move two connected handles

In other editing programs you'll get a preview of the shots before and after the cut like so (pic from Davinci Resolve) :

![image](https://user-images.githubusercontent.com/12694995/43505571-50b3abe2-95a2-11e8-8f26-338c8285aaa3.png)

Do you have an idea of how to do that in Blender, like rendering and overlaying thumbnails of the frames before and at the cut in the editor? Blender's py API is powerful so there's probably a way to access the rendered image data - not sure you can render two frames at the same time.

**Comment by 3pointedit** [comment]
How about using the offset frame preview? Its the little ghost button? You
could split preview into 2 and offset one of them by 1 frame

**Comment by NathanLovato** [comment]
It could well work! Gotta try to see how splitting the preview area dynamically could work, but it should be ok.

**Comment by 3pointedit** [comment]
You could possibly do any 2 roller or trim head type. Edit point strip tail
and strip head frames or, slip trim the head and tail of the same strip.
But this is more useful when you can see the surrounding edit points as
well. In this case its a four thumbnail representation which offset won't
assist.

**Comment by NathanLovato** [comment]
Yeah and another thing to consider is rendering in this case: there's some buffer ahead of the time cursor and of the past frames you watched, but rendering two frames that are far apart on a single CPU core will likely be a bit sluggish. Anyway I'm going to spend some time working with resolve and blender in parallel to see where we can get the biggest productivity boosts.

**Comment by 3pointedit** [comment]
Having head and tail frames is nice but the best way to trim an edit is,
while you have loop play over edit running. So that you are getting
feedback while shifting the edit this way or that. Requires an edit nudge
key for left or right by 1 frame and a multiple of, for example 10 or 15
frames to jump while trimming. Usually this loop play feature is a default
before/after  value of perhaps 1 to 2 secs either side. Its specifically
Trim Mode.

**Comment by NathanLovato** [comment]
See the work by @tin2tin for reference (thanks 😄) https://gist.github.com/tin2tin/b7fd08762d1d8290626ee299488e2798?fbclid=IwAR3hYBr8npLzMUUBfrBp6cfIB3v5Ai1wB89omYIoWdflvdOWf2H1-GiugAo
