### ISSUE TITLE
Add operator to register and remove keybindings

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#18]
Add 2 operators, accessible from the add-on, preferences, to register and unregister keymaps.

- [ ] parse keymaps from a dict (and/or a JSON file?) for easier editing
- [ ] duplicate the active keymap, rename to Power Sequencer
- [ ] register and replace existing shortcuts if need be
- [ ] Print collisions to the console
- [ ] Report to the user?
- [ ] add buttons to the add-on prefs

Should there be an option to register the full keymaps or by operator type (e.g. markers, editing, etc.)?

**Comment by NathanLovato** [comment]
How should the add-on handle keyboard shortcuts? A lot of Blender add-on force their keymaps, even brute delete other add-ons' mapping every time blender starts and honestly mess up your profile. 

At the same time, downloading a pre-made shortcut scheme means if you want to customize yours, you've got to start over every time a new version comes out, or to port your changes.
Power Sequencer changes a lot of mappings, including some default ones. So:
1. Should we stick to a predefined keymap file?
2. Should there be buttons to e.g. create a copy of the current profile with new keyboard shortcuts from the add-on in the prefs?

**Comment by doakey3** [comment]
This feature has been added with [9c51d25](https://github.com/GDquest/Blender-power-sequencer/commit/9c51d25327d34744b15f0b07e3dcf8779560c4a2)

**Comment by NathanLovato** [comment]
Thank you very much, let's close the issue for now then :)
