### ISSUE TITLE
Create markers from selected strips

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#201]
Create and name one marker for each strip in the selection

**Comment by 3pointedit** [comment]
This would be really useful for a shot list or EDL. Like with the "markers to image placeholders" you already have, it would be great to have the shots listed with their inpoint timecode (and duration). If the list were sortable by name, comment field or timecode, you could jump to any position in the edit quickly. Sadly I don't think there is anywhere in Blender to contract a little spreadsheet like doc? When creating  the markers it would be nice to choose a list of pre-defined keywords, these might include Scene no., shot/take, shot type (CU WS 2 Shot etc.), talent name, dates etc...

**Comment by NathanLovato** [comment]
Your request sounds very different from this issue. I won't work on a shot list as you can find in other NLEs - it's a lot more work than you'd expect to make it work well. E.g. Blender won't read or write video metadata, you'd have to use a separate python library and code the entire system. 
If you need these types of features, bins and all, you'll want to use another program.

**Comment by 3pointedit** [comment]
Sorry I didn't mean to infer that you should add camera-side metadata. I am wondering if you are adding sign posts to an edit? I just thought it would be useful to be able to search for a place on the timeline that you have marked as Scene01 for example. It would be great for tutorial videos, when you want to keep track of particular sections that need further work.

**Comment by NathanLovato** [comment]
Ah you mean some markers list in some menu? It would probably end up in the properties panel as it's the only one area where there's space for it. Please open an issue to clarify your idea, and if you have a screenshot to give some reference (e.g. from another program) that would help a lot
