### ISSUE TITLE
Use markers as searchable Chapters or Range keywords

### ISSUE THREAD

**Issue by 3pointedit** [GDquest/Blender-power-sequencer#208]
When editing a complex timeline in the VSE, the strips often all look the same. This is especially true when the strips are just duplicates of the main master clip (for example when cutting a tutorial screen grab). So it would be useful to select a series of strips that make up a scene or chapter of the edit, then assign a marker to it. 

> For example, Keyword 01 - Introduction, Keyword 02 - Part one, etc.

A marker would be placed at the start of the first selected strip and another is placed at the end of the last selected strip. This would denote a range and the 2 markers would be a pair or group. In the past I have used a Color Effect Strip (labeled) to show these ranges.

These keywords (in/out point range) would appear in a searchable list in the properties panel(?) so that you could jump to each section just by selecting that keyword. 

A further development might allow you to select the strips defined by the keyword range, then you could copy paste them to a new location. Even better you could move them by simply moving the keyword in the list.

**_Issue 01:_** Could the outpoint marker be aware of the last selected strip's duration so that it would move dynamically when the last strip is shortened/lengthened or moved?

**_Issue 02:_** Could markers be color coded for different tasks? For example if we want to show that a section is to be altered or replaced? Perhaps it could have a specific keyword applied that could be searched in the list?

Here is a link to a [brief tutorial](https://larryjordan.com/articles/fcp-x-rediscover-the-timeline-index/) describing the use of timeline markers in FCPX.

**Comment by 3pointedit** [comment]
Just to clarify about the color strip as keyword range. This image shows a metastrip that has a color effect (labelled) for each keyword, it has a specific color per task. The strips are placed in a metastrip so that they don't consume all of the available working tracks. You can still visualise the relative locations and lengths of the strips when the metastrip is scaled up to fit a tall channel. 
![keyword range](https://user-images.githubusercontent.com/25983373/44628312-6af2b880-a980-11e8-9d9b-7f947b1303cb.jpg)

You can even use the Outliner to search in the metastrip.
![searchable](https://user-images.githubusercontent.com/25983373/44628357-62e74880-a981-11e8-995d-457ecf097ecd.jpg)

**Comment by 3pointedit** [comment]
I notice that the Outliner allows you to rename strips that are in a metastrip (normally unavailable unless you are in the metastrip). This would make renaming selected strips easier. And I wonder if you can search and rename markers in this way?
![vse timeline list](https://user-images.githubusercontent.com/25983373/44652487-56212e00-aa2f-11e8-8ae5-bfb15b3ac22e.PNG)

**Comment by NathanLovato** [comment]
I've thought about this again, and about ways we could handle this. I don't have a solution that's not hacky, prone to breaking with vse updates, and that would integrate well with the vse's design.

I think the way to go would be to use scene strips: we already have some tools to wrap selected edits in a scene. But scene strips still have limitations so  it's far from ideal for now.

In the future the situation might be different but for now, I don't want to invest time working on this feature. I'll close the issue for now. Not that the suggestion is bad, thanks for the detailed feature request :smiley:
