### ISSUE TITLE
Constrained zoom

### ISSUE THREAD

**Issue by ChameleonScales** [GDquest/Blender-power-sequencer#209]
Do you think this is doable?
https://blender.community/c/rightclickselect/hrbbbc/

**Comment by NathanLovato** [comment]
It might be possible horizontally only, with a big hack. As far as I know you don't have control over the view's extents in Python, so you can't create a custom zoom tool - you have to call Blender's built-in zoom instead. It would probably be a lot easier to do on Blender's side, in C.

**Comment by ChameleonScales** [comment]
Ok, thanks. I will wait for an opportunity to ask for this feature to the blender core developers.

**Comment by NathanLovato** [comment]
You're welcome! The zoom operator/code seems to be the same across all regions (graph editor etc.) so even if there's no VSE maintainer at the moment it's a change someone could make, if you find a dev. who's interested. It don't think it's very complicated to add either.

**Comment by NathanLovato** [comment]
I'll close this one as we can't really solve it with the add-on. Suggestions and feedback to help us improve the tools' UX welcome! Thanks for your issue
