### ISSUE TITLE
Add UI to BPSrender (integrate in Blender's VSE)

### ISSUE THREAD

**Issue by eplipswich** [GDQuest/blender-power-sequencer#210]
You may or may not know this already, but there's actually a multithreaded render tool called Blender Render Controller, which is a lot more user-friendly than multithreaded render via command-line: https://github.com/RedRaptor93/BlenderRenderController/

Your integration of BPSRender into Power Sequencer is cool, but to be honest, I was actually hoping you would make a render tool as user-friendly as Blender Render Controller. but turns out that it's command line. So maybe it would be even cooler if you can integrate Blender Render Controller into the Power Sequencer (you'll have to liaise with RedRaptor93 on this).

Video of how Blender Render Controller works for your reference: https://www.youtube.com/watch?v=Kdvq1CzOPfM

**Comment by NathanLovato** [comment]
I know render controller. I don't want us to go with an external program: once BPSrender has been well-tested, the next step is to integrate it in Blender's VSE so you can render and see the progress bar at the top of the window, almost like normal.
I'm leaving this to contributors though, as I've got enough tasks to work on already.
