### ISSUE TITLE
Design a menu in the Sequencer's toolbar

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#213]
Design a menu with Power Sequencer's tools. This will make the features and shortcuts discoverable. Aditia offered to help with this, big thanks to him 😄

If you can help with UX design, we're still looking for help on #90 (design a panel for power sequencer) and #89 (Improve the existing contextual menu) 

![image](https://user-images.githubusercontent.com/12694995/44782563-92d15e80-abc2-11e8-939b-08b285c14a89.png)

**Comment by aditiapratama** [comment]
![image](https://user-images.githubusercontent.com/982553/45684396-616c0300-bb70-11e8-93a6-4e82dcc9403e.png)

This layout is not sorted yet, any comment/feedback are welcome

**Comment by NathanLovato** [comment]
Thanks much @aditiapratama, closing this for now. Let's open new issues to discuss improvements - e.g. adding icons, reordering...
