### ISSUE TITLE
Make Still Image: Trim to gap between strips

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Blender-power-sequencer#214]
Currently the `Make Still Image` feature creates a strip that, or seems to, have a constant length. I think that would be a good improvement if we could be able to change this behavior to something like:

- If there is a gap between the selected strip and the next one in the same channel it will take only the length of the gap
- Otherwise (or if the gap is smaller then X frames) it will go to the next available channel above the current selected strip

Wachu think about this behavior? :smiley:

**Comment by NathanLovato** [comment]
> If there is a gap between the selected strip and the next one in the same channel it will take only the length of the gap

Good if this is optional. There should still be the option to force a given length (but auto-size by default)
Another option is to add a gap of the size of the still's length with `sequencer.gap_insert`. But I think finding the first channel above is fine. You can use `power_sequencer.channel_offset` to move a strip a channel up -> it'll find the first empty channel for you
