### ISSUE TITLE
Trim the content of a metastrip upon ungrouping it

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#215]
From @3pointedit:

> It would be good to trim contents of metastrip to length of metastrip when breaking them out again. 
>
> Or even place a cut (at the position of the metastrip end) on the strip inside that covers the end of the metastrip. So that you can put an audio fade on synced audio strips that are grouped inside a metastrip

I vouch for the first option, as ungrouping a metastrip in the middle of an edit can get the strips all over the place. My only question is: should this be the default? Should this override Blender's built-in behavior, like we've done with Copy and Paste? I'd rather avoid having switches and too much configuration in the add-on's preference.

**Comment by 3pointedit** [comment]
It is unlikely to become default Blender process because there are 2 states to choose from, Decompose original length or trim to Meta length. When it becomes a 2 step process I notice that it generally doesn't get made that way.

**Comment by NathanLovato** [comment]
I was asking if this tool should replace Blender's Un-meta automatically or not.
