### ISSUE TITLE
power_sequencer.remove_gaps: add support for markers

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#216]
Find and ripple all markers after each gap

**Comment by 3pointedit** [comment]
Does this make the markers dynamic with the movement or length changes, of strips on the timeline?

**Comment by NathanLovato** [comment]
No, markers are not attached to strips. There's no easy way to do that, and markers are so basic in Blender they aren't the right tool for the job imo.
