### ISSUE TITLE
Add tool to cut with the keyboard even when nothing's selected

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#218]
Video editing programs typically do something like that, when you jump to cut or move the time cursor, they auto-select the clips the cursor overlaps (in the channel you're working on). Pretty important for fast edits

**Comment by 3pointedit** [comment]
Although they typically allow modal operation. For example choose cut
- only of parented or synced strips
- only of type eg. Audio strips or video strips
- constrain to channel or group of channels
- only meta strips

**Comment by NathanLovato** [comment]
You can use `select_strips_under_cursor` to automatically find and select the strips under the cursor when nothing is selected
This could replace the default cut command, just adding some way to auto select strips (see #239 )
