### ISSUE TITLE
Replace Shift ➡ and Shift ⬅: move 1 second forward/back

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#221]
<kbd>Shift</kbd> <kbd>➡</kbd> and <kbd>Shift</kbd> <kbd>⬅</kbd> jump to the start/end of the timeline. It's not very useful, and inconsistent with <kbd>➡</kbd> and <kbd>⬅</kbd> that nudge the timeline 10 frames forward/back.

How about replacing this with moving 1 second in time? this would be more consistent with other NLEs

**Comment by 3pointedit** [comment]
I agree it should be a variation of the 1 frame skip. It would be nice to
define the amount of skip in x numbet of frames. Sometimes you want 10
frames, other times you want a second or more. The Jump to end and Jump to
head should be the up and down arrows, without modifier as I dont think
they are used for anything else.

**Comment by 3pointedit** [comment]
Oops I just realized that Up/Down arrow are KF jumps.

**Comment by NathanLovato** [comment]
closed by https://github.com/GDquest/Blender-power-sequencer/commit/b50085ca77335ff4657355245eddca453a7be1c5
