### ISSUE TITLE
delete_direct: auto select linked strip under the mouse if nothing's selected

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#223]

**Comment by 3pointedit** [comment]
Unclear, do you mean delete _both_ parts of a linked strip if only one part is selected? How could you override this if you want to keep a part? Perhaps you want to delete the audio by itself?

**Comment by NathanLovato** [comment]
You just select if you want to delete precisely. From the title: `auto select [ ... ] if nothing's selected`
