### ISSUE TITLE
Review keymaps for faster editing

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#23]
There are powerful editing features in Blender + the add-on, but the default shortcuts try to stay true to how Blender works in general. I tried to follow the same logic with the power-sequencer keymaps, but now it's time to review the full scheme and provide more accessible shortcuts.

A few ideas, coming from other programs:

- I/O to do in and out trims (use smart trim operator) instead of Ctrl K, Alt K
- [ and ] to change playback speed step
- U and Ctrl R for undo/redo (Vi-style)?

- [ ] Use a global modifier to apply operator to all channels instead of selected strips*
- [ ] Use a modifier to represent left and right side operations
- [ ] Find better shortcut for the contextual menu
- [ ] Review shortcuts for all tools

* E.g. Shift K to cut all, Shift I to trim all in, Shift O to trim all out, etc.

See https://github.com/GDquest/Blender-power-sequencer/issues/18 for related work

**Comment by NathanLovato** [comment]
Jump to cut is on Pg up/down by default. Move it to a more convenient place: [ and ], or < and > (,.) maybe ?

**Comment by doakey3** [comment]
Perhaps we should leave the Blender shortcuts as they are (unless they're in the way of a better operator in Power-Sequencer). Users can always change Blender default the shortcuts themselves if they want.

**Comment by NathanLovato** [comment]
Yeah, that's right.

**Comment by NathanLovato** [comment]
We've actually done work on the keymaps since the issue was opened. We'll keep improving them over time but at least the shortcuts got some improvements over the past few months.
