### ISSUE TITLE
BPSproxies: improve progress reporting, use a progress bar

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#242]
For now progress report gets a little heavy when you're working on larger projects:

![image](https://user-images.githubusercontent.com/12694995/45530145-327a2800-b824-11e8-9752-cd42ab4a3bc9.png)

@razcore-art would you have a recommendation on how to show progress? We have % based progress reporting on the current video being rendered by ffmpeg. I think a single progress bar could show ffmpeg's progress on the current video, with some text showing the total. Is it possible to update two lines like this in the console?

![image](https://user-images.githubusercontent.com/12694995/45530399-5f7b0a80-b825-11e8-995e-d2e541e0329d.png)

**Comment by razcore-art** [comment]
In theory anything is possible, I have to get acquainted with the code. For BSPrender I'm using https://github.com/tqdm/tqdm which is very easy to work with and does the heavy lifting

**Comment by NathanLovato** [comment]
I'm fine with having tqdm as a dependency here as well. Currently you'll see the reports just print a XX% text for each video, printing dozens or hundreds of lines if you generate many proxies like I do for a project.

**Comment by NathanLovato** [comment]
Feel free to make improvements that feel most useful to you

**Comment by razcore-art** [comment]
I'll close this issue since I moved [BPSProxy](https://gitlab.com/razcore/bpsproxy) to own repo and we can keep track of stuff there. At the moment it has a **totals** progress based on the number of files being processed
