### ISSUE TITLE
BPSProxies: render multiple proxy sizes at a time

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#243]
It's the last missing feature before we can integrate it to Blender: FFmpeg can output multiple versions of the video in parallel. The tool just needs support for an array of sizes as input arguments, and the Video class to expand the command for each input size: https://trac.ffmpeg.org/wiki/Creating%20multiple%20outputs

**Comment by 3pointedit** [comment]
Do these encodes happen in the background or do they prevent blender from
working?
