### ISSUE TITLE
Icons for PowerSequencer toolbar menu?

### ISSUE THREAD

**Issue by libreartist** [GDquest/Blender-power-sequencer#247]
Hi, I'm a graphic designer, unaware of Blender Icon guidelines and the list of icons the new toolbar may need. Could you point me in the right direction, if it may be of any use?

**Comment by NathanLovato** [comment]
Hey there! Thanks for dropping by. Blender ships with standard icons, so to start with it'd be ideal to reuse as many as possible. We'd need a hand to pick the right icon for each menu action and make it easier to browse. If you want to help with this, there's a tool in Blender to copy the icon names so we can put them in the menu's code:

![image](https://user-images.githubusercontent.com/12694995/45730864-3be20680-bc0f-11e8-9a7d-020994d1e77d.png)

Would you like to give a hand with this? Designing new icons would take a lot more work. I'd definitely greatly appreciate that! But we should first work with available icons, and only have you design extra ones as necessary, if you're up for it.

Please tell me what you'd like to do.

**Comment by NathanLovato** [comment]
As far as the icon guidelines, here's a starter post. As you'll see it's a little technical: the developers use a shared script to make sure that everyone uses the same colors, gradients, and filters: https://developer.blender.org/T38757

**Comment by libreartist** [comment]
Thank you. Sorry to reply late.. let me see what I can do.

**Comment by libreartist** [comment]
Though the icon guidelines of Blender was fun to study, I understand the concern for reusing the existing icons as best as possible. I took up some hints from https://github.com/GDquest/Blender-power-sequencer/commit/210451ae42750dad18d9e01e723cc02192dc54d7, as to whichever toolbar operators may be need matching icons. Still, I was able to match icons for all the operators that I could find in https://github.com/GDquest/Blender-power-sequencer/commit/210451ae42750dad18d9e01e723cc02192dc54d7. I tried to match the ecosystem of icons assigned to default operations of Blender's menu bar and other parts, yet I had to reinvent the meaning of some of the icons (which is up to your discretion) based upon their looks. Sometimes, the similar operators of the different contexts had to look the same (almost, all the operators dealing with "selection" had to be assigned with the icon RESTRICT_SELECT_OFF, for instance). Hence, the long list of operators matched with the respective icons, as follows:

"Power Sequencer" SEQ_SEQUENCER

"power_sequencer.synchronize_titles" SORTALPHA
"power_sequencer.set_timeline_range" ARROW_LEFTRIGHT
"power_sequencer.cycle_scenes" SCENE
"power_sequencer.channel_offset" AUTOMERGE_ON
"PS_MT_trim" LINE_DATA
"PS_MT_strips" NLA
"PS_MT_select" RESTRICT_SELECT_OFF
"PS_MT_render" RENDER_ANIMATION
"PS_MT_playback" PLAY
"PS_MT_markers" MARKER
"PS_MT_file"  FILE
"PS_MT_edit" MODIFIER
"PS_MT_audio" SOUND

"Playback Speed" TIME

"power_sequencer.increase_playback_speed" PREVIEW_RANGE
"power_sequencer.decrease_playback_speed" RECOVER_LAST
"power_sequencer.change_playback_speed" MODIFIER

"Strips Operation" NLA

"power_sequencer.add_transform" RNA_ADD
"PS_MT_strips_speed" TIME
"power_sequencer.concatenate_strips" CONSTRAINT
"power_sequencer.fade_strips" IMAGE_RGB_ALPHA
"power_sequencer.swap_strips"  ARROW_LEFTRIGHT
"power_sequencer.toggle_selected_mute"  (MUTE_IPO_ON, MUTE_IPO_OFF)
"PS_MT_strips_fades" IMAGE_RGB_ALPHA

"Speed" TIME

"power_sequencer.add_speed" PREVIEW_RANGE
"power_sequencer.unspeed" RECOVER_LAST

"Fade in/out" IMAGE_RGB_ALPHA

"power_sequencer.fade_add" ZOOMIN
"power_sequencer.fade_clear" X

"Select" RESTRICT_SELECT_OFF

"power_sequencer.border_select" BORDER_RECT
"power_sequencer.select_linked_effect" CONSTRAINT
"PS_MT_deselect" RESTRICT_SELECT_ON
"PS_MT_grab" HAND
"PS_MT_snap" SNAP_ON

"Deselect" RESTRICT_SELECT_ON

"power_sequencer.deselect_all_left_or_right" ARROW_LEFTRIGHT
"power_sequencer.deselect_handles_and_grab" HAND

"Grab" HAND

"power_sequencer.grab" HAND
"power_sequencer.grab_closest_cut" FORCE_DRAG
"power_sequencer.grab_sequence_handle" HAND

"Snap" SNAP_ON

"power_sequencer.smart_snap" SNAP_GRID
"power_sequencer.snap_selection_to_cursor" RESTRICT_SELECT_OFF

"Edit" MODIFIER

"PS_MT_delete" X
"power_sequencer.remove_gaps" X
"power_sequencer.copy_selected_sequences" COPYDOWN

"Delete" X

"power_sequencer.delete_direct" X
"power_sequencer.ripple_delete" X

"Markers" MARKER

"PS_MT_marker_delete" x
"power_sequencer.go_to_next_marker" TRIA_RIGHT_BAR
"power_sequencer.markers_as_timecode" TIME
"power_sequencer.snap_marker_to_cursor" SNAP_ON
"power_sequencer.set_preview_between_markers" SEQ_PREVIEW
"power_sequencer.markers_snap_matching_strips" NLA

"Delete Marker" X

"power_sequencer.marker_delete_closest" X
"power_sequencer.markers_delete_direct" X

"Render" RENDER _ANIMATION

"power_sequencer.make_still_image" FILE_IMAGE
"power_sequencer.render_for_web" URL

"File" FILE

"power_sequencer.open_project_directory" FILE_FOLDER
"power_sequencer.save_direct" FILE_TICK
"power_sequencer.import_local_footage" FILE_MOVIE
"power_sequencer.set_video_proxies" EXTERNAL_DATA

"Trim" LINE_DATA

"power_sequencer.trim_three_point_edit" TRIA_DOWN
"power_sequencer.trim_to_surrounding_cuts" SNAP_PEEL_OBJECT
"PS_MT_mouse" RESTRICT_SELECT_OFF
"PS_MT_preview" SEQ_PREVIEW

"Mouse Trim" LINE_DATA

"power_sequencer.mouse_cut" MOD_WIREFRAME
"power_sequencer.mouse_trim" LINE_DATA

"Preview" SEQ_PREVIEW

"power_sequencer.preview_last_cut" SEQ_PREVIEW
"power_sequencer.preview_to_selection" SEQ_PREVIEW

"Audio" SOUND

"power_sequencer.align_audios" ALIGN
"power_sequencer.toggle_waveforms" RNDCURVE
"power_sequencer.mouse_toggle_mute" (MUTE_IPO_ON, MUTE_IPO_OFF)
"PS_MT_crossfade" IMAGE_RGB_ALPHA

"Crossfade" IMAGE_RGB_ALPHA

"power_sequencer.crossfade_add" ZOOMIN
"power_sequencer.crossfade_edit" MODIFIER
"power_sequencer.crossfade_remove" X

**Comment by libreartist** [comment]
If any icon assigned is inappropriate and be reassigned, or to be designed from scratch (I, sometimes, envy the cross-platform appeal of Resolve's icons), kindly suggest, I owe, since I'm a huge beneficiary of this project. Thank you...

**Comment by NathanLovato** [comment]
Thanks much for the help! Next time though, when I ask you "Please tell me what you'd like to do", please do that first. Your work is much appreciated and helpful, but we could have both saved time starting with a tiny bit of extra discussion.

The icons are in! Not all options needed one, so sometimes in submenus I didn't use them - when they made the menu harder to browse:

![image](https://user-images.githubusercontent.com/12694995/45787615-2b826800-bcb1-11e8-9919-ee03dcf074c8.png)

Could you give me your name and Github email address? So I can add you as a contributor to this repository. You can send it to me in private via [twitter](https://twitter.com/NathanGDquest) if you don't want it to be visible here. Note though that everyone's email is in the git log and commits, so anyone can see it. But without your name and email, you won't appear as a contributor.

**Comment by libreartist** [comment]
Ok..
libreartist
libreartist@tutanota.com

**Comment by NathanLovato** [comment]
There you go 😄

![image](https://user-images.githubusercontent.com/12694995/45788115-992f9380-bcb3-11e8-8f96-ef63f23181d0.png)
