### ISSUE TITLE
Blender Velvets merger?

### ISSUE THREAD

**Issue by libreartist** [GDquest/Blender-power-sequencer#248]
Hi, all! Bear me, I am quite descriptive in my appeal, yet I want to suggest a thing, which is awesome, considering the potential of Blender. I believe, the Blender Power Sequencer was started with appeal to cover every good VSE plug-in (at least, their capability) that we come across. And, the projects like Power Sequencer is one of the reason, I strongly believe, the VSE still exists in Blender, despite 'this' (https://code.blender.org/2015/11/the-2-8-project-for-developers/). I was a serious user of Resolve (like @NathanLovato ) and Sony Vegas Pro (before they crippled it). Then, after becoming the @libreartist that now I am, I started to love Blender for its versatility. Before I found Power Sequencer, I found Blender Velvets (https://github.com/szaszak/blender_velvets), which made my workflow easier, especially with the project's plugin called 'Blue Velvet' with which you can export the audio tracks as .ardour, to get them edited and mixed in the powerful Ardour (thus, attaining the right audio editing support for Blender). Both projects try to create video proxies in a sort of similar way; both have assigned keyboard shortcuts for video operations (though, Blender Velvet's implementation is quite different); Power Sequencer could use the capability of the Blue Velvet plugin still. And, the maintainer of Blender Velvet's maintainer @szaszak is friendly too. So, is there any way the two projects can be merged, since it could rightfully accelerate Blender VSE's progress? (Yet, I'm counting on what Blender 2.8's new python API has to offer for plugin development, and the update of 2.8's VSE is still under speculation.)
Thank you.

**Comment by NathanLovato** [comment]
If you want the functionality of blue, just install the plug-in. There's no way I know of to support import and export with Daws in a generic way. Ardour is mostly popular among Linux users so it shouldn't be the default.

Developing programs work like you seem to think it does. You can't just merge two different  design philosophies and codebases easily. There are opposite ux decisions in both add-ons or suites.
Also, the 2.8 API probably won't change at all for the vse.

PS doesn't try to replace all plugins. It just tries to give you an enhanced editing experience with more or less coherent UX. It's good to have multiple options for users with different tastes or needs.

**Comment by libreartist** [comment]
Thank you :-)
