### ISSUE TITLE
Selections: Add linked (in Blender: add a default shortcut)

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#251]
E.g. Shift L to add linked under the mouse cursor (L) to the selection

**Comment by NathanLovato** [comment]
Already in Blender: bpy.ops.sequencer.select_linked_pick(extend=True) -

**Comment by razcore-art** [comment]
I have a different proposal which is more in line with the regular (3D view) operation. L in 3D view adds to the selection list (in edit mode), Shift L on the other hand subtracts from the list. Honestly I don't know why this isn't a toggle (like L to add to selection if unselected and L to subtract from selection if already selected).

So these are my proposals:
1. make L add to selections and Shift L to subtract from selections
2. make L add to both add and subtract from selections (toggle)

If we go with 2. there's no need to override the default Shift L (lock strip). If we go with 1. it's more in line with the 3D view edit mode operation. For me 2. seems better.

**Comment by NathanLovato** [comment]
Option 2 seems better to me as well. Go ahead!
