### ISSUE TITLE
Error in Set Videos Proxies

### ISSUE THREAD

**Issue by varkatope** [GDquest/Blender-power-sequencer#263]
I get this error when I try to use the Set Videos Proxies command:

```
Traceback (most recent call last):
  File "C:\Users\tech\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\power-sequencer\operators\set_videos_proxies.py", line 32, in execute
    prefs = context.user_preferences.addons[__package__].preferences
KeyError: 'bpy_prop_collection[key]: key "power-sequencer.operators" not found'

location: <unknown location>:-1
```

Blender 2.79b, Windows 10 64-bit

Setting proxies from Blender still works fine. I've tried removing spaces in the custom proxy folder name, changing its location. I've tried downloading 1.1 release, which didn't even show up in Blender after activating and restarting, then upgrading to Master from the addon's updater function. I've tried downloading the Master zip from Github directly (which affects the addon's file path since it appends '-master' to the folder in addons from that point on. Other Power Sequencer functions seem to work fine, though I haven't tried all of them.

**Comment by NathanLovato** [comment]
The feature is obsolete, I have to remove it
