### ISSUE TITLE
Strips are inconsistent after operator snap_selection_to_cursor

### ISSUE THREAD

**Issue by Blezyn** [GDquest/Blender-power-sequencer#264]
Consider this case:

![before snap](https://user-images.githubusercontent.com/42165833/47457280-59daf200-d7df-11e8-9c20-13832b5dbdb6.png)

Post snap_selection_to_cursor the state is:

![after snap](https://user-images.githubusercontent.com/42165833/47457316-6cedc200-d7df-11e8-8639-dfa09850704a.png)

Why this happens:
Take a look at this image, the same case before the usage of the operator :

![before snap processed](https://user-images.githubusercontent.com/42165833/47459000-b04a2f80-d7e3-11e8-8e97-a7215a2b2749.png)

While D3 < D1 < D2 the operator will behave undesirable. More specific D1 is the distance between the time cursor and the frame_start of the leftmost strip of the selection (according to the source code), D2 is the distance between the frame_start of the leftmost strip of the selection and the frame_final_end of the  of the rightmost strip of the selection and D3 is the distance between the frame_final_end of the leftmost string and the frame_start of the rightmost strip.
All this for 2 strips. For more, things get more complicated. The basic idea is that, you can't move a strip at the left by a specific amount that will force it to land on another strip. So with more strips it is very likely that at least 2 strips will collide.

If the special cases of D3 = D1 or D1 = D2 occur, then the operator works properly.
Ofcouse, because the length of a strip is always >= 1, the case D3 = D2 can never happen. So D3 != D2.

Possible solution: 
Using bpy.ops.transform.seq_slide(value=(x, 0)) you can move a whole block of selected strips without getting this problem. The direction is just the sign of input x. I think this implementation won't be longer in lines of code or more complex than the current one.

- Note 1: It is a good practise that, before applying a translation like that, first we run select_related_strips on the selection, and then we translate it, so the possible effect strips will stay consistent.

**Comment by NathanLovato** [comment]
I'm aware of the issue but thanks for the detailed report! Feel free to open a PR if you have the time 🙂
