### ISSUE TITLE
Suggestions for naming improvements and some bugs

### ISSUE THREAD

**Issue by tin2tin** [GDquest/Blender-power-sequencer#276]
I've tested the Power Sequencer header menus with a bunch of meta-strips in the sequencer on Windows 8 in Blender 2.79B. Many of my findings are smaller things and things to consider so instead of spamming with creating a lot of issues I'll just post a list of my findings. Here they are:

- [ ] Edit > Copy Selected Sequences: Error

- [ ] Add a shortcut for opening the Power Sequencer menu(Like the add menu's shift+a) at mouse point or else doesn't "Select all strips left or right" make any sense. Same thing with Mouse Cut(brillant function btw.) 

- [ ] I feel there needs to be more consistency in the naming conventions. Ex. cut('k') should be used like "split"/"slice"/"razor" in other apps. When removing material in Avid it is called "Lift" without ripple and when ripple deleting it is called "Remove" - other apps call it "delete" and "ripple delete" - so "Mouse Cut" maybe should be called "Mouse Lift"?

- [ ] Trim to surrounding strips: error with one meta-strip selected.

- [ ] Maybe trim should be renamed to "ripple delete", "remove" or something else? For me, the "trim" word seems to be connected to what is called grab operations in Blender.

- [ ] I do not understand how "Change Playback Speed" supposed to be accessed from the menu? 

- [ ] Set timeline range only sets range start?

- [ ] The user-friendliness of many of the grab and trim operations would improve a great deal if the time cursor was ex. locked to ex. strip end when grabbing a strip handle or locked to the "Mouse Cut" end during that operation, so you can see where you're actually removing. 

- [x] Are all of the assigned shortcut keys visible in the menu?

**Comment by NathanLovato** [comment]
> I feel there needs to be more consistency in the naming conventions.

The names should follow Blender's vocabulary. In Blender's VSE, you have knife, cut, tri
There certainly are some inconsistencies in the add-on, and it'd be helpful

**Comment by NathanLovato** [comment]
Thanks for your error reports, I'm marking them as suggested enhancements now. I'm also editing your initial post to add checkbox to separate the issues - this way it'll be easier to track what's been addressed and what hasn't been done yet.

**Comment by NathanLovato** [comment]
I'm closing this issue as it's a little old now, we've ported the addon to 2.80 and fixed a lot of bugs. Most points don't apply anymore.
Thank you very much for taking the time to write all these! In the future, if you report bugs or suggestions again, could you please keep it to one per issue? Otherwise, it's hard to triage and close them.
