### ISSUE TITLE
Additions Proposal for a few operators

### ISSUE THREAD

**Issue by samytichadou** [GDquest/Blender-power-sequencer#277]
Hi fellow developpers of this great addon !
I'm currently writing some code for the vse with blender edit addon (which aims at adding some UI and database system for VSE) and i have some timeline operators which i don't feel they belong to this addon (it's better if it just focus on database...) so i thought i'll propose these functions here, i think they can fit in power sequencer, but of course, up to you to decide :)

here's my fork :
https://github.com/samytichadou/Blender-power-sequencer/tree/master/operators

Here's a little list :

- export sequence operator : an attempt to have a classic export helper panel, letting the user choose the place of the exported video and the export settings in only one panel. I could add here an integration for the BPS renderer, if needed
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/export_sequence.py

- go to in out operator : when multiple clip selected, go quickly to first frame of all, or last frame of all with the playhead
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/go_to_in_out_selection.py

- move selected strips : a simple operator to move clips forward/backward 1 or 10 frames, or up and down, easy to bind to shortcut to have a kind of alt+left/right (premiere pro's fashion)
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/move_selected_strip.py

- select by channel : an operator to select entire channel in one action, you can add selection to previously selected clip, and toggle select/deselect. It could be bind to shortcut with numpad for example to easily select deselect big chunks of your edit
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/select_by_channel.py

- select handles : go to next or previous cut by selecting only handles of a clip, or both handles on an edit, allowing to quickly trim the edit
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/select_handles.py

- select left right : select all clips right or left from active selection to quickly make some extra space in the timeline
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/select_left_right_from_active.py

- select playing : select currently playing clip (the operator doesn't take muted clip into account, unless user tell it to)
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/select_playing.py

- set scene settings : a all in one floating panel to set dimensions, framerate, pixel rate... for the current scene
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/set_scene_settings.py

- toggle audio mute : a simple operator to put the audio mute or not on key binding
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/toggle_audio_muted.py

- toggle audio scrubbing : a simple operator to put the audio scrubbing or not on key binding
https://github.com/samytichadou/Blender-power-sequencer/blob/master/operators/toggle_audio_scrubbing.py

I'm not familiar with github, so don't hesitate to tell me if the fork is not the way to do it ;)

Cheers !

**Comment by NathanLovato** [comment]
It all looks great to me! Forking is the way to go. You want to create one commit per new feature ideally, and in general one branch/PR per feature or per group of related features, depending on their scope. In this case it could be:

- One PR for the export tool
- One per new panel and related operator
- One for the scene and timeline settings (including audio mute/scrubbing)
- ...

A few quick notes about style:

- In Python and for blender python, the standard is PascalCase for class names and `snake_case` for functions, methods, variable names.
- @razcore-art is going to make a proposal to standardize the add-on's codebase. We don't have strict conventions just yet, but we're going to add that soon.

It's best to use built-in operators, that are probably written in C. E.g.
```
    for s in scn.sequence_editor.sequences_all:
        s.select=False
        s.select_left_handle=False
        s.select_right_handle=False
```
⬇
```
bpy.ops.sequencer.select_all(action='DESELECT')
```

Unlike methods, that belong to a class, functions are general utilities that should:
    - generally be used in multiple places in the codebase
    - take input, return an output, and not do things directly

When you have a function that modifies strips, it generally should be a method in your operator:

```py
class SelectHandles(bpy.types.Operator):
[...]
    def execute(self, context):
[...]
        FuncSelectHandles(self.right)
        return {"FINISHED"}
```    
⬇
```py
class SelectHandles(bpy.types.Operator):
[...]
    def execute(self, context):
[...]
        return self.select_handles()

    def select_handles(self): # It's part of the operator, so it has access to its state and properties, e.g. self.right
[...]
        return {'FINISHED'}
```

**Comment by NathanLovato** [comment]
There's a task to integrate BPSRender in Blender's UI. Currently, it's assigned to @razcore-art, but if you'd like to tackle it with your export panel, that'd be much welcome! See #210

**Comment by samytichadou** [comment]
Hey thanks for your quick answer and for all these intels, i'll try to get around these infos to rewrite and reorganize the operators !

just a question about the function within the operator, my first thought was to be able to use those functions through other operators (select handles function could be handy in some other case for example) is it still possible in this way ? sorry for noob question, no coder, just enthusiastic over here ;)

And yeah, if it's not yet done, i'll be glad to integrate BPS render as soon as i've got time !

**Comment by NathanLovato** [comment]
You can call your own operators from Python. They register under bpy.ops. + the bl_idname, e.g. bpy.ops.power_sequencer.select_under_mouse. Doing this calls the operator's `execute` method

**Comment by NathanLovato** [comment]
Please tell me if I can help you. You can hit me up anytime on Discord: https://discord.gg/dKUX7m3 (that's the power sequencer channel)

**Comment by samytichadou** [comment]
thanks a lot ! i don't have much time but i'll tell you if i encounter any problem as soon as i'm on it ! cheers !

**Comment by NathanLovato** [comment]
Closing this for now as there's been no update since 2018. If you still want to contribute, could you please open one issue or PR per feature?

There are some improvements to power sequencer 1.3 and blender 2.80 that remove the need for some of these operators as well, that's in part why I'm closing here. Thanks for offering your help in any case. You're always welcome if you find time to participate in the future :)
