### ISSUE TITLE
Ripple delete: error if the strip is the input of a transition effect

### ISSUE THREAD

**Issue by tin2tin** [GDquest/Blender-power-sequencer#295]
The bug on deleting cross dissolves is affecting the ripple delete function in power sequencer. Watch this gif for more info: https://devtalk.blender.org/uploads/default/original/2X/2/23e76ebe87d4116e111db0b585ea93202cbb4d5c.gif

**Comment by NathanLovato** [comment]
Thanks for the report 🙂

Issue:

![image](https://user-images.githubusercontent.com/12694995/49508807-fad0c880-f8c6-11e8-9505-2994ea325dbc.png)

![image](https://user-images.githubusercontent.com/12694995/49508794-f3112400-f8c6-11e8-8d27-3ee8047a0c46.png)
