### ISSUE TITLE
10,12,14 bit HDR video rendering for BPS

### ISSUE THREAD

**Issue by Corruptinator** [GDquest/Blender-power-sequencer#303]
This is probably advanced and or challenging, and probably not sure if this is the right spot to ask but is it possible for the BPSRender have the capability to render out any video in **High Dynamic Range**?

I've been doing some research about exporting videos with HDR metadata in 10, 12, or 14 bits and went through a pretty complicated process of understanding how it works.

Before I get straight to the point, I'd like to explain what Blender is _missing_: The problem that I found out is that pretty much any common, computer monitor only displays sRGB/Rec. 709 colorspaces and it is prohibitively expensive to buy an HDR nits reference monitor. However there is a cheaper alternative... Using color grading luts, it is very doable to view HDR videos (video colors nearly dull in regular sRGB) in the Blender's VSE Image Preview. Using an open-source, online lut generator: **LutCalc**, I experimented around with a HDR sample image until I cross-referenced and confirmed the closest HDR-to-SDR viewable lut:

![image](https://user-images.githubusercontent.com/5027750/50511129-3df30700-0a41-11e9-8417-0273bd62a196.png)

Using HLG as the trick to down-convert HDR to SDR, this can allow video editors such as Blender's VSE to be able to view HDR videos in the Image Preview, after converting it into a .spi1D file:

![image](https://user-images.githubusercontent.com/5027750/50511346-27997b00-0a42-11e9-99a7-460012db2948.png)

Then moving to the HDR-to-SDR.spi1D file to Blender's Color Management folder. (EX: {path-to}\Blender\2.79\datafiles\colormanagement\luts)

Next, the config.ocio file needs to be edited to include the following:

```
displays:
  Rec2100:
    - !<View> {name: HLG, colorspace: 2100_HLG}

active_displays: [sRGB, DCIP3, Rec709, Rec2100, XYZ, None]

  - !<ColorSpace>
    name: 2100_HLG
    family: display
    equalitygroup:
    bitdepth: 32f
    description: |
      Displays in HDR at HLG.
    isdata: false
    allocation: uniform
    allocationvars: [-0.125, 1.125]
    to_reference: !<GroupTransform>
      children:
        - !<FileTransform> {src: [HDR-to-SDR-file].spi1d, interpolation: linear}
```

Finally, Blender's Color Management can be modified along with exposure to view HDR videos in almost similar colors:

![image](https://user-images.githubusercontent.com/5027750/50511683-75fb4980-0a43-11e9-9b69-1de1cdbecf99.png)

I can't guarantee that its perfect or not, and that there are better ways to change the colorspace; but I did experiment through HDR cross-referencing through various image viewers such as VLC or etc. With viewing the correct colorspace in the VSE Image Preview, any video editor would freely edit HDR videos in an HLG Color Managing workspace. Afterwards, they can change the Color Management and Exposure level back to default before rendering, and that is where BPSRender comes into play.

I know for a fact that Blender's built in FFMPEG encoder only encodes videos in 8-bit, SDR videos. but taking upon a look into Blender Power Sequencer I realize in theory that it may be possible to send out frames to FFMPEG externally using BPSRender, but to get it encoded with HDR Metadata included is a different matter. As of FFMPEG 4.0 update and above, I've discovered that videos can be encoded into HDR using this command (through Trial-and-Error):

`ffmpeg -i [Video-Goes-Here].mkv -c:v libx265 -tag:v hvc1 -preset ultrafast -crf 5 -pix_fmt yuv420p10le -x265-params "colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,400):max-cll=1000,400" [HDR-Video-Exported-Render-Here].mkv
`

(Note: **libx265**[HEVC] is the file format required for HDR encoding, **VP9**[webm] is also possible but needs further research. The "yuv420p10le" is a Pixel Format to encode in 10-Bit HDR, I don't know what the others are... Other settings are what color primaries, color transfer, color matrix, are supposed to be set at. Master display and max-cll are optional)

So if BPSRender utilize HDR rendering through FFMPEG, maybe it could use new commands to allow  HDR encoding. For example:

```
-hdr [10,12,14]
-mdisplay [true, false]
-max-cll [true, false]
```

Pretty long to explain but figured I give out full details to help clarify and support the curiousity for the potential to edit HDR videos in Blender and using BPSRender to export videos with HDR metadata. Also, if exporting into an image sequence, it would need to be in **32-bit float** for _.hdr_ or _.png_ image files; and the files needs to be saved in either _.mkv_ or _.mp4_.

Here is both the modified .spi1D file and the .lutcalc file in a zip folder for a quick setup in LutCalc to download the generator HDR-to-SDR lut file, in case anybody wants to experiment. A modified config.ocio file is included in case nobody wants to dive into editing the opencolor syntax code. Be sure to back up the original "config.ocio" file before replacing it with the one provided.

P.S. Nice work on the Blender Power Sequencer addon by the way! Looking forward to 1.3!
P.S.S. LutCalc was made by Ben _Turley (cameramanben)_: https://cameramanben.github.io/LUTCalc/

[HDR-to-SDR_Lut.zip](https://github.com/GDquest/Blender-power-sequencer/files/2714629/HDR-to-SDR_Lut.zip)

**Comment by NathanLovato** [comment]
This is way out of scope for BPSRender and this project. PS is all about allowing people to edit faster, building upon the VSE's supported set of features.
I don't want to maintain features almost nobody would use or that nobody in the dev team would use, and that still too few devices support (HDR displays are still far from mainstream)

**Comment by Corruptinator** [comment]
Oh, nevermind. Sorry.

**Comment by NathanLovato** [comment]
No problem, thanks for the detailed post, really! It's just we have very limited resources so we must focus our energy where it can make the biggest difference. Also things like these shouldn't be hacked in but properly added to Blender itself imo.

**Comment by Corruptinator** [comment]
Understood.  :)
