### ISSUE TITLE
Auto-generate proxies after importing local footage

### ISSUE THREAD

**Issue by davcri** [GDQuest/blender-power-sequencer#311]
Generating proxies is a common thing that we do when we start working on a new video: we can streamline the current workflow by adding an interactive dialogue box asking something like:

> "Do you want to generate proxies for the imported footage?"

This issue was created after a short discussion in #302.

### 1. The user wants to generate proxies after "Import Local Footage"

1. The user run "Import Local Footage"
2. A dialogue box appears

[Optional]: we can consider also adding an option to enable "Automatically generate proxies when importing footage", so expert-users can also skip the second step (this could be another issue).

### 2. The user wants to generate proxies after importing a single file

1. The user imports a single file (eg: by drag&drop)
2. A dialogue box appears

**Comment by NathanLovato** [comment]
> [Optional]: we can consider also adding an option to enable "Automatically generate proxies when importing footage", so expert-users can also skip the second step (this could be another issue).

There are now proxy preferences in the add-on, to set strips proxies. We can:

1. Add a checkbox in the preferences to auto-generate proxies with blender after importing local footage. It's as simple as calling `Rebuild proxy and timecode indices` if the preference is checked
2. Check if bpsproxy is installed
3. If so, add either a drop-down or an extra checkbox to choose the rendering backend: Blender native proxies or bpsproxy (+ preset to use)

This only works with import local footage as bpsproxy and this ops work in a similar way: with one folder, they import everything next to the blend file. bpsproxy isn't meant to support everything blender's builtin proxy system can do, just to allow you to generate ~lightweight proxies fast, optionally using your GPU (nvidia's nvenc), making proxy rendering at least 20-40x faster than with Blender here.

----------------------

The importing a single file part should be a different task, as it'd be a completely different system. We'd need to use the scene_update_post handler to check for newly added sequences, set them proxy, and rebuild. For bpsproxy, we'd need to add support for individual file paths.

-----------------

In either case, I'd avoid showing a pop-up menu. That shouldn't be the default.
