### ISSUE TITLE
Removing a cross fade alters the strips duration/start frame

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Blender-power-sequencer#312]
When removing a cross fade between 2 strips they automatically extend their end/beginning handles. I dunno if this is expected due to #204 but it is really annoying, because more than often I have to reposition the handles because I want the gap. Especially when I made a cross with a strip that I don't want to cross anymore and I want to cross with a different strip and move strips around.

![cross_report](https://user-images.githubusercontent.com/10171059/51184572-cf74cc80-18bb-11e9-818d-9a77e926707b.gif)

**Comment by NathanLovato** [comment]
Could you add labels when you post an issue to our repos?

Yes, that's normal, because you're supposed to use Ctrl Alt C: auto crossfade, with power sequencer. That's the only way we can make adding/removing crossfades work like in a more traditional NLE, and the most productive way to work with them.

There's no easy way around it if you want the productivity boost: we'd have to keep track of the strips start time, but if you use the add menu you directly call in blender's internal add crossfade which doesn't allow us to track any info.

**Comment by NathanLovato** [comment]
Blender has limitations for video editing so I'd prefer the addon to provide an efficient workflow even if we make a few tradeoffs. There are quite a few things like these right now, lots of tools need some polish.

**Comment by NathanLovato** [comment]
No update here so closing for now.

**Comment by henriiquecampos** [comment]
Hey, reopening the discussion as I find another unexpected bug going on and I think is due to the topic in this issue.


![cross](https://user-images.githubusercontent.com/10171059/52013165-83cd4000-24c3-11e9-8e63-d62b78bde3d2.gif)

It would be a really cool improvement if there was a way to toggle this behavior. I can implement this setting.

**Comment by NathanLovato** [comment]
There needs to be some more thoughts on how to handle this. transitions get messed up in blender if you delete one of the inputs. So you should always remove the effect strip first until the UX gets some improvement in blender itself.

We can change the shortcut for our delete operator do this and leave the default delete from blender bound to X. E.g. use Alt X for PS's delete. What do you think?

**Comment by henriiquecampos** [comment]
Sounds like a plan, but won't this sorta of break the usability a bit? Although I think that having distinct shortcuts for default and plugin behaviors sounds good indeed.

**Comment by NathanLovato** [comment]
It'd just be reverting X to do delete without confirmation, and e.g. Alt X to "smart delete" or something.
