### ISSUE TITLE
Port the add-on to blender 2.8

### ISSUE THREAD

**Issue by brousselle** [GDquest/Blender-power-sequencer#313]
- [ ] Create a branch for the port
- [ ] Refactor registering classes
- [ ] Use 2.8's class naming conventions

See https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API

**Comment by NathanLovato** [comment]
We're not planning to port to 2.8 just yet as the VSE is being worked on and still needs some fixes. Then, as far as I know, we can't have the faster playback hack in 2.8 which limits your productivity a lot.

I've had a brief exchange with Richard, VSE's new maintainer, and we could make the add-on available as part of Blender 2.81. But we've got to discuss the design and future of the add-on for that first, then change quite a few things. We could really use some help to get there.

Anyway, for now, there's work to do improving the tools and UX in priority.

**Comment by brousselle** [comment]
I fully understand the issue here. But just to highlight my problem: i only use very few features from BPS like power cut, or the new "killer" gap remove with a music locked stripped (really love that one). I have migrated to 2.8 for all modeling stuff, and also migrated to "right select mode" as this is the default now.
So going back to VSE in 2.79 makes nodes with my fingers, and interface looks now very old.
I also use quite a lot 2d and 3d tracking with eevee. 
So for me 2.8 is now the default, and i already really miss BPS ;)

Anyway i am very happy there is a new core maintainer for VSE, and that you guys already discussed with him. Pretty exciting stuff to come !
Thanks for your work guys !

**Comment by NathanLovato** [comment]
Turns out now we can port all the features. So let's make this one of our next priorities.
I'll edit the description to list everything we have to do

**Comment by brousselle** [comment]
Awesome :D Thx Nathan ;)

**Comment by NathanLovato** [comment]
Done with #324 :D
