### ISSUE TITLE
Removing cross fade between effect strips throws error

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Blender-power-sequencer#315]
When we try to delete a cross fade between [any strip type] and a Transform we get the following error

```
Traceback (most recent call last):
  File "/home/henrique/.config/blender/2.79/scripts/addons/power-sequencer/operators/delete_direct.py", line 35, in invoke
    return self.execute(context)
  File "/home/henrique/.config/blender/2.79/scripts/addons/power-sequencer/operators/delete_direct.py", line 40, in execute
    bpy.ops.power_sequencer.crossfade_remove()
  File "/home/henrique/Downloads/blender-2.79b-linux-glibc219-x86_64/2.79/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/henrique/.config/blender/2.79/scripts/addons/power-sequencer/operators/crossfade_remove.py", line 49, in execute
    strip_1.frame_final_end = effect_middle_frame
AttributeError: bpy_struct: attribute "frame_final_end" from "TransformSequence" is read-only

location: /home/henrique/Downloads/blender-2.79b-linux-glibc219-x86_64/2.79/scripts/modules/bpy/ops.py:189



location: <unknown location>:-1

```

So it is related to these line:

https://github.com/GDquest/Blender-power-sequencer/blob/master/operators/crossfade_remove.py#L40-L42

https://github.com/GDquest/Blender-power-sequencer/blob/master/operators/crossfade_remove.py#L49-L50

Since some effect strips, such as the Transform and probably the SpeedControl as well as Gaussian Blur I guess, are not supposed to have different start/end frames than the strip they affect, i.e. their start/end is read-only, we get these errors.

I think one fix could be to not work on effect strips, but I don't know the impact of this in the actual behavior.

**Comment by NathanLovato** [comment]
You need cross between effect strips. E.g. anything with animation through the transform effect. We should have some try/except block(s) to handle different types of strips.

**Comment by henriiquecampos** [comment]
> You need cross between effect strips

Yep, I meant to make this operator ignore effect strips, this `RemoveCross`
