### ISSUE TITLE
The Future of Power Sequencer

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#316]
Power Sequencer grew bigger than it was meant to be at first. It does quite a few things, and with close to 70 modules, its feature set is a little wide and shallow.

We kept adding new operators and kept tinkering with the workflow. It's time to do some polishing work. Moving forward, I'd like us to make the add-on more efficient, more accessible, and easier to maintain.

Be it as a designer or as a writer, you achieve great results not just by building up, but by trimming down as well. By removing the superfluous details. I want us to do this in the next version.

Pin-pointing what Power Sequencer is and is not will make it easier to document the add-on and to produce great tutorials. By limiting its scope and focusing our efforts on what saves the most editing time, we can build tools that will allow everyone to work with the VSE at the speed of thought.

This is why we're opening this discussion. What should Power Sequencer be about?

If you want to edit a short film or a movie, Blender VSE isn't the best tool for the job right now. But if you're editing screen recordings, more or less linear videos, or tutorials, it can be a really productive tool.

The only issue is that by default, the VSE splits simple editing operations in different tools, bound to different keys. As a result, it can take a few keystrokes to do one simple edit, like selecting, cutting, deleting a strip, and removing the newly formed gap.

That's why to me, Power Sequencer should focus on saving you as much time as possible using core editing tools: combining these basic separate operations for you, based on the context. It should help you get a smooth experience when you import, select, cut, trim, fade, and export your project.

It already does this adding keyboard, mouse, and stylus-friendly tools, but also automating selections and smartly rippling edits based on the context. In the future, I'd like it to do it better, and not try to do a bit of everything. If another area of the Sequencer needs more tools, we should consider contributing to an existing add-on like the VSE Transform Tools, or creating another add-on dedicated to that task.

Here are my ideas for the future of Power Sequencer:

- Port to 2.8 and rename classes etc. to follow Blender's convention (SEQUENCER_OT_*)
- Focus all our attention on the editing workflow and saving keystrokes: cutting, trimming, moving strips around...
- Adapt the UX to better support left-click default in 2.8
- Drop the least used and least useful features. Even I don't use all of them, and talking with video editors, I noticed people mostly use a few core editing tools like MouseCut.
- Improve and unify existing operators in terms of UX. Things like auto-select if you don't have anything selected and ripple edits.
- Make the tools easier to discover and use drawing to make PS more user-friendly
- Create and observe stricter code guidelines and conventions for our Python projects

Feedback, discussion, and contributions are welcome. We're first going to port the add-on to Blender 2.8. In parallel, we're looking to see if and how we can contribute to Blender's VSE directly with Richard, its new maintainer.

**Comment by davcri** [comment]
Wow lots of things.

Generally speaking I agree that focusing on polish it's a good thing. I used BPS for a year to edit video tutorials and it's absolutely amazing for this task.

>Drop the least used and least useful features

Agree, I use a subset of all the features.

>Port to 2.8 and rename classes etc. to follow Blender's convention (SEQUENCER_OT_*)

I'm not familiar with 2.8, does PS requires a lot of changes to work with the new Blender version?

If someone wants to contribute to the porting is there any recommended resource (apart the official [Blender2.8 api documentation](https://docs.blender.org/api/blender2.8/))?

> Create and observe stricter code guidelines and conventions for our Python projects

Was there any specific issue with the current code?

**Comment by brousselle** [comment]
This is very good news !
I switched to 2.8 a few weeks ago, and i can tell you that BPS really makes the job if you want to be fast and efficient: i do feel it as i can't use it anymore in 2.8 ;)

The direction you want to take now is really what i am waiting for: powercut, gaps, selections, trimming, and the one i love most "locked music strip".

So excited about this future ! Thanks Nathan for making this happen !

**Comment by NathanLovato** [comment]
Can you both tell me which features you use the most and what improvements we could bring to these features? Anything that would help you work more productively.

**Comment by davcri** [comment]
Well I use almost any operator except these ones:

- Cycles scenes: I don't use multiple scenes
- Cut strips under cursor (<kbd>K</kbd>)
- Edit crossfade
- Mouse trim
- Ripple delete
- Trim to Surrounding Cuts

Regarding improvements, I don't have any good suggestion at the moment. PS is perfect for my basic video editing needs.

Actually I have some bug (one regarding crossfades, another one regarding dozens of fades being added to a strip) but I'll open a specific issue when I have a good report for them.

**Comment by brousselle** [comment]
Here are the things i use most:
- add transform (*)
- delete  direct
- fade strips
- mouse cut (including cut gaps) (*)
- mouse trim (*)
- save direct
- refresh all
- locked strip not beeing cut by mouse cut. (*)
- bpsrender (*)

*: top priority for me ;)

**Comment by NathanLovato** [comment]
@davcri do you use the marker and scene strip operators? If you don't use multiple scenes though you're not using scene strips either, right?

You'll probably want to start using all the features you said you don't use, they're all time savers. E.g. press G to move a crossfade like any other strip: that's Edit crossfade. If you use mouse editing tools, you use mouse trim as well. Trim to surrounding cuts is a big time saver.

**Comment by davcri** [comment]
No I don't use scene strip operators.  
Sometimes I use markers (just to annotate some part that I need to edit later, eg: adding an image overlay).

> You'll probably want to start using all the features you said you don't use, they're all time savers.

I have to try, but as I said before my needs are fairly basic.  

Just to clarify: I'm not saying that I want to remove those features :smile:

**Comment by razcore-art** [comment]
I'm actually using strips scenes quite a lot and am hiding/showing them if things get slower, but I haven't used them in combination with BPS so I can't say much about the operators.

Scene strips are really useful for doing quick previews if you're doing motion graphics/vfx sort of things, instead of rendering them out then reimporting/refreshing. Some times I make scenes for masking as well instead of the 2D mask since scenes give you much more freedom in terms of what types of transitions/fx you can do.

**Comment by NathanLovato** [comment]
@razcore-art The operators I'm talking about above are specific tools to convert a selection to a VSE scene (a separate timeline), merge the content of a scene into another... they're not about cutting and trimming.

That was because compositing in Blender using the node compositor is per-scene, you can't use it per strip or on a metastrip. So with these tools you can do more advanced compositing on part of a video, use tonemapping/color grading (also only works per-scene, not per strip)...

All editing operators should already support scene strips.

Yes, scene strips are useful, but there are core limitations. I think that, as with markers, that:

- Coding a productive set of tools would take a lot of work for little increase in productivity
- These are core Blender issues, so they should be fixed in Blender
- It's likely VSE contributors will add things like node compositing support per strip or strip markers at some point, making our work obsolete. Unlike Power Sequencer's editing UX and auto-select workflow imo

That's why I'm talking about dropping the operators listed above. But again, it's up for discussion. It seems David didn't even know about some of them, and nor did you. Maybe nobody ever used them besides me 😄

**Comment by cspeterson** [comment]
@NathanLovato 
>That's why I'm talking about dropping the operators listed above. But again, it's up for discussion. It seems David didn't even know about some of them, and nor did you. Maybe nobody ever used them besides me

*blinks*

These will really improve my life, now that I know about it. So count another person who had no idea 🙂

**Comment by cspeterson** [comment]
> That was because compositing in Blender using the node compositor is per-scene, you can't use it per strip or on a metastrip. So with these tools you can do more advanced compositing on part of a video, use tonemapping/color grading (also only works per-scene, not per strip)...

@NathanLovato wait are you saying it's possible to then use the vse output from the newly-created scene in the compositor?? how? this is something I haven't been able to figure out for a while!

**Comment by NathanLovato** [comment]
@cspeterson No, unfortunately, you can't send the output from the VSE directly to the compositor. You'll need some add-on to batch render the scenes and import the corresponding image sequences to the compositor. There's an add-on to send individual video strips to the compositor.

**Comment by brousselle** [comment]
Well, i think we are quite a lot dreaming that one day it will be possible to setup compositing nodes on a per strip style !
one day ;)

**Comment by NathanLovato** [comment]
Now there's a maintainer and contributors, there's hope, really. Richard opened a discussion about having most VSE operators in Python in Blender itself, which would open the door to more developers, while he and others can focus on a more performant back-end. And it seems it's likely to happen: https://devtalk.blender.org/t/python-based-operators-for-vse/5788/2

**Comment by cspeterson** [comment]
@NathanLovato 😲 that would be wonderful if it came to pass!

**Comment by wernight** [comment]
Given that Blender 2.8 has a FFmpeg encoder, could this (or the FFmpeg multi-thread encoding) get merged in Blender directly?

**Comment by NathanLovato** [comment]
This is an add-on. We can submit it as an official add-on to package with Blender, but that's about it. We've discussed contributions with the maintainer and people on blender.chat. For now, the focus is on getting Blender 2.80 out. The next steps for the sequencer and what contributions are wanted or not moving forward isn't clear.

**Comment by wernight** [comment]
I admit it's slow and there are many issues, but it's still the most powerful opensource video editor IMO. I'll make some video about it soon.

The best quality I managed to get was using PNG 16bit and then ffmpeg it specifying the color model. However this takes a LOT of disk space and wastes time, for no good reason. I wonder if bpsrender could achieve that. Previously the frame renderer hack could do that I heard (now it's been removed for a while).

**Comment by NathanLovato** [comment]
bpsrender can render anything - it just spawns several blender processes. It will still write all the pictures, then encode them in a separate pass. But it can use e.g. 12 blender processes to render with 12 cores. It uses your blend file's render settings. After you're done, you'll have to remove the files manually.

Here's the command I use to render a blender project in a given folder. I have a different problem from you, a super slow internet connection, but I need to do the same: render from Blender, compress the footage well with ffmpeg so I can upload it in a reasonable timeframe:

```sh
bpsrender -w 6 *.blend && ffmpeg_compress_nvenc --delete *.mp4 && mv *.mp4 ~/Videos/youtube-exports/ && rm bpsrender/
```

Power Sequencer or BPSRender can't solve foundational issues with the VSE: you need to rewrite the software's C core to make it possible to just hit render and have fast rendering from within Blender.

**Comment by NathanLovato** [comment]
Now we're getting a bit off-topic.

I started contributing a bit to Blender directly. For Blender 2.81, I'll be coding some features in Python. The goal is to slowly move features from the add-on to Blender itself, and only use the add-on to customize the workflow, make it faster to edit... to make tweaks that are not wanted in Blender because they're not consistent with the rest of the program. E.g. removing confirmation when you delete a strip or save.
