### ISSUE TITLE
Features to remove in Power Sequencer 1.3

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#317]
As we discussed in #316, we want to focus on the most useful features in Power Sequencer and remove the least useful ones. I went through all operators and picked these ones to remove, or to have as part of another add-on.

In short, it's mostly scene and scene strips related tools. My thought process behind this is:

- Markers aren't great in Blender. We can't have per-strip markers, colored markers, etc., and these are all core limitations. Even I, who used the add-on a lot and wrote all the marker-related operators (iirc), don't get to use them that often.
- Scene strips slow down renders a lot, we can't merge their content back fully into the main scene to fix that... and with the current toolset the workflow isn't that efficient. It would take a lot of extra development to make the tools worth the maintenance work.

The files list:

- align_audios (+ dependencies)
- set_timeline_range (not used anywhere)
- playback_speed_set.py
- Marker-related tools
  - synchronize_titles (to markers)
  - marker_delete_closest
  - marker_go_to_next
  - markers_as_timecodes
  - markers_create_from_selected
  - marker_snap_to_cursor
- Scene related tools
  - scene_create_from_selection
  - scene_cycle
  - scene_merge_from
  - scene_open_from_strip
  - scene_rename_with_strip

**Comment by razcore-art** [comment]
Like I mentioned on discord, we could probably add needed functionality to markers (including colors & per-strip options) with the use of custom properties if it's something useful enough.

**Comment by NathanLovato** [comment]
This kind of work should really be done in Blender's core. And it's likely to happen sometime in the future, if more people start to work on the VSE. 

More importantly, I think it'd take quite a bit of work to create a good system. So I'd rather not roll our own replacement for markers.

**Comment by NathanLovato** [comment]
Another operator to consider removing: `playback_speed_set.py`: increase and decrease playback speed works well with <kbd>[</kbd> and <kbd>]</kbd>

**Comment by NathanLovato** [comment]
Scene strips got perfs improvements in 2.80, gotta test this on new video projects.

**Comment by NathanLovato** [comment]
I removed a few things, rewrote some code. As there hasn't been too much feedback on this issue, I'm leaving the feature set as it is now for the next release
