### ISSUE TITLE
ImportLocalFootage directory code is Windows only

### ISSUE THREAD

**Issue by davcri** [GDquest/Blender-power-sequencer#33]
For example, I was testing the `ImportLocalFootage` from `load_files.py` (with the intention of using it and then writing some doc 😄) and at [Line 78](https://github.com/GDquest/Blender-power-sequencer/blob/05c2ebe1594dcf5d767cc7542b06b266abde5555/load_files.py#L78) there is : 
``` python
folders[folder_upper] = directory + "\\" + folder
# On my GNU\Linux OS:
# folders={'IMG': '/home/daenn/blender_projects/test\\IMG'}
# invalid path!

```
I don't understand why you use two backslash. Maybe it's a Windows thing ? 

---

However code  can be easily improved using  [os.path.join](https://docs.python.org/3.6/library/os.path.html#os.path.join) to create a path:

``` py
folders[folder_upper] = os.path.join(directory, folder)
# On my GNU\Linux OS:
# {'IMG': '/home/daenn/blender_projects/test/IMG'}
```

*Note*: using `os.sep` you will get the right path separator for every platform:
``` py
print(os.sep)  
# Linux =>  '/'
# Windows => '\'
```

**Comment by NathanLovato** [comment]
Ah, it's old code. I just got started with python when I made the add-on. Thanks! If you find anything, feel free to file a bug. There's definitely room for improvement with things like the `poll` methods and some windows-only code in the add-on.

**Comment by NathanLovato** [comment]
Should be fixed, could you please give it a try? https://github.com/GDquest/Blender-power-sequencer/commit/0c0ee414488eb9e78121d5c74c46f70557017987

**Comment by davcri** [comment]
It works. I just tried importing images in the sequencer ;)


![schermata da 2017-08-27 18-44-31](https://user-images.githubusercontent.com/6860637/29752092-d0850e70-8b57-11e7-9efe-6926c3b4b562.png)

**Comment by NathanLovato** [comment]
Thanks much!

**Comment by davcri** [comment]
`ImportLocalFootage` doesn't work again on Linux (I'm starting to think that you hate this OS 😝), not tested on other OS.

A little workaround can be found here: https://github.com/davcri/Blender-power-sequencer/commit/38ce01e859585af4941fe1dff0d6b54473eb5dc5
In the workaround I forced the keyword argument `directory` to `//`. Blender seems to use `//` for relative paths to the .blend file.

PS: reading the Blender Python API I also discovered the it has a module dedicated to paths management, maybe it can be useful to refactor the code ? https://docs.blender.org/api/current/bpy.path.html

**Comment by NathanLovato** [comment]
Nah it's just another old class that could use some refactoring. I've patched it a few times to fix edge cases and probably broke multiplatform paths along the way. E.g. initially it didn't store filepaths to prevent reimporting everything.
It's one of these classes where I wish I got a quick review from a more experienced blender/python dev, to know how to best handle it. I'd bet you can store the paths as custom properties in the blend file somewhere instead of exposing them to the user.

**Comment by davcri** [comment]
> Nah it's just another old class that could use some refactoring. I've patched it a few times to fix edge cases and probably broke multiplatform paths along the way.

Got it. 
As it is a low-priority issue, I'll work on the doc with the workaround, hoping that it doesn't change the behavior of the the importer 🤞

**Comment by NathanLovato** [comment]
Seems you only have the img import working here. Let's check this tomorrow, I'll have a bit of time to dive back into the code. Hit me up anytime on Discord in the late morning/afternoon.

**Comment by davcri** [comment]
I just tried and it works also with "AUDIO" and "VIDEO" folder importing 😉

**Comment by NathanLovato** [comment]
Okay makes sense there: I fixed a nasty bug with the img folder recently (images import a bit differently from video and audio, as you can import individual strips or image sequences)
