### ISSUE TITLE
trim_to_surrounding_cuts.py: Shortcut Shift Alt Action Mouse doesn't work in 2.8

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#330]

**Comment by razcore-art** [comment]
See https://github.com/GDquest/Blender-power-sequencer/issues/332#issuecomment-472360073, I didn't see find a bug.

**Comment by NathanLovato** [comment]
Figured it out: I had 3-button mouse emulation on (working with a tablet), and in 2.80, MMB triggers scrolling by default. Not a bug
