### ISSUE TITLE
Replace ACTIONMOUSE and SELECTMOUSE in source code

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#332]
Some tools and shortcuts relied on ACTIONMOUSE etc. in Blender 2.79, which doesn't exist in Blender 2.80
SELECTMOUSE is now LEFTMOUSE, and ACTIONMOUSE should be RIGHTMOUSE

![Screenshot from 2019-03-12 21-22-40](https://user-images.githubusercontent.com/12694995/54233329-06a6d900-450d-11e9-9f43-48276ae476db.png)

**Comment by razcore-art** [comment]
There's no `ACTIONMOUSE`/`SELECTMOUSE` left in the source code that I could find, maybe you didn't invoke `trim_to_surrounding_cuts` properly? the shortcut is `LEFTMOUSE + SHIFT + ALT` and it works fine as far as I can tell

**Comment by NathanLovato** [comment]
All good then!
