### ISSUE TITLE
Import Local Footage - on Mac OS

### ISSUE THREAD

**Issue by gbarnabic** [GDquest/Blender-power-sequencer#338]
This isn't a big issue but when you import using Import Local Footage on a Mac it imports a hidden file called .DS_STORE.  Also I noticed that images are put on two lines instead of one as I would expect. https://gyazo.com/06e254db27b5452d19e00af8944e6493 

I'm using version PS 0.1.4 Blender2.79b

**Comment by NathanLovato** [comment]
It's fixed, but only in the latest master, so in Blender 2.80.

**Comment by NathanLovato** [comment]
Thanks for the report!
