### ISSUE TITLE
Fix grammar in add_speed and regenerate README

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#359]
Change the string in the source code and regenerate the README: https://github.com/GDquest/Blender-power-sequencer/pull/358

There's a typo: it's -> its

**Comment by pacovila** [comment]
Sorry, I had previously changed the README directly because it's not very usual to keep track of generated files. I realize that the platform requires it.

**Comment by NathanLovato** [comment]
No worries, I appreciate that you took the time to open a PR 🙂
