### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by KesaiArts01** [GDquest/Blender-power-sequencer#360]
When I click on checkbox this error appears:
![image](https://user-images.githubusercontent.com/51276652/59153420-612dd380-8a2f-11e9-957e-34f33844c383.png)
EDIT: Why I can't install it on 2.79? Just on 2.80

**Comment by NathanLovato** [comment]
Because the latest version of the addon is only for Blender 2.80, which is incompatible with 2.79. You'll have to use an older version of the addon: try 1.1
