### ISSUE TITLE
BPSProxy needs pip3 install instead pip

### ISSUE THREAD

**Issue by cgvirus** [GDquest/Blender-power-sequencer#382]
with pip install this error occurs
```
 bpsproxy -h
Traceback (most recent call last):
  File "/usr/local/bin/bpsproxy", line 6, in <module>
    from bpsproxy.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/bpsproxy/__main__.py", line 12, in <module>
    from .call import call, call_makedirs
  File "/usr/local/lib/python2.7/dist-packages/bpsproxy/call.py", line 39
    def call(cfg, clargs, *, cmds, **kwargs):
```
pip3 works
O/S Debain 10

**Comment by NathanLovato** [comment]
Ah it's not that it requires pip3, it's that on your system, you're using Python 2.7 as the default - it's the Python version that the commands `python` and `pip` will use. Then you have `pip2` and `pip3` to use either explicitly. On Windows it's most common that the default python interpreter is version 3 so just doing `pip install ...` will work.

@razcore-art do you mind if I open repositories for bpsrender and bpsproxy on GDQuest?

**Comment by cgvirus** [comment]
Alright thanks.
