### ISSUE TITLE
BPS proxy: add option to output files to a specific directory

### ISSUE THREAD

**Issue by cgvirus** [GDquest/Blender-power-sequencer#383]
Is it possible to throw all proxy outputs in a specific directory with commandline argument?

Reason: It is quite possible to get footage from banks and servers. And creating proxy in those and finding them later to delete is quite unproductive.

Finding: In Blender we have Proxy Setting>Project>Directory

This ensures all proxy will go to a global directory. This is convenient as we can just delete the whole proxy folder when project is done. Also managing proxies will be simpler.

**Comment by NathanLovato** [comment]
No you can't. We're keeping the tool simple so it's easy for us to maintain. Someone could contribute the feature but we're not going to add that: hopefully, BPSProxy and BPSRender will get obsolete at some point, when multithreaded support gets fully added in the VSE.

By the way, this isn't the repository for BPSProxy, it's there for now: https://gitlab.com/razcore/bpsproxy

**Comment by cgvirus** [comment]
Alright, then I will make a simple ffmpeg encoder directly to work with blender as a separate plug and will knock you again.

**Comment by NathanLovato** [comment]
Yup, note the problem isn't about coding the feature, but coding it cleanly as part of bpsproxy. You can add support that by adding a cli option and bypassing the `find_files` function in the `__main__.py` file: https://gitlab.com/razcore/bpsproxy/blob/master/bpsproxy/__main__.py

The file list parsed from the cli should just have the same format: a list of valid file paths.

**Comment by NathanLovato** [comment]
Opened it there: https://github.com/GDquest/BPSProxy/issues/2

**Comment by Serkan-devel** [comment]
(You could have selected to redirect this issue without copy and pasting it over)

**Comment by NathanLovato** [comment]
Good to know for next time, thanks
