### ISSUE TITLE
BPS proxy: add option to proxy specific files, not entire directories

### ISSUE THREAD

**Issue by cgvirus** [GDquest/Blender-power-sequencer#384]
This is also important. As making proxy of the whole footage bank will also take space for unused footage.

**Comment by NathanLovato** [comment]
This would complicate the code and maintenance for a feature few would use. If someone wants to properly code it, contributions are welcome! But we've got too much work otherwise.

**Comment by NathanLovato** [comment]
We just moved the BPSProxy and BPSRender repositories from gitlab to our GitHub organization. I'll close the issues here and open them in their respective repos:

- https://github.com/GDquest/BPSRender
- https://github.com/GDquest/BPSProxy
