### ISSUE TITLE
Adding Gamma Cross (Ctrl+Alt+C) Doesn't Work Properly

### ISSUE THREAD

**Issue by filibis** [GDquest/Blender-power-sequencer#387]
I followed [this video tutorial](https://youtu.be/8FvXxmU3Vjg?list=PLhqJJNjsQ7KFjp88Cu57Zb9_wFt7nlkEI&t=67) but it doesn't add gamma cross to fade in/out as shown. Instead the gamma cross is squeezed in between strips. IS that a bug or am I doing something wrong?

![gamma_cross](https://user-images.githubusercontent.com/26340322/62624478-d16fad00-b92b-11e9-85bb-f71e55efda31.jpg)

I use Blender 2.80

**Comment by NathanLovato** [comment]
This is normal, I improved the tool since this old tutorial. Now you're using an unreleased version of the add-on. This is closer to how crossfades work in pretty much every video editing program: keeping the strips, using the frames on either side of the inputs
