### ISSUE TITLE
Workflow Improvement using Pie Menu

### ISSUE THREAD

**Issue by aditiapratama** [GDQuest/blender-power-sequencer#391]
I've been working using BPS and would like to add more improvement in workflow by implementing pie-menus.

So far what I did was :
- [ ] adjust proxies size operators, adjust both all strips and `proxy_render_size` to common use, like 25% or 50% (new operators)
- [ ] adjust the offset of strips channel
- [ ] add/edit crossfade

I've assigned the keymap to <kbd>Shift</kbd><kbd>W</kbd>

If anyone feels like adding more useful workflow, feel free to comment as I preparing the PR.

Cheers 😸

**Comment by NathanLovato** [comment]
Thanks, please open a draft PR anytime for feedback and review

**Comment by NathanLovato** [comment]
Are you still working on this or should I close the issue?

**Comment by aditiapratama** [comment]
Still working on it...I'll update here as soon as possible

**Comment by NathanLovato** [comment]
Okay thanks!

**Comment by NathanLovato** [comment]
I'm closing the issue as there's been no PR or update since 2019. If you'd still like to finish it, please open a PR and we'll reopen the issue.
