### ISSUE TITLE
Remove transition cross or gamma cross from color strips

### ISSUE THREAD

**Issue by rolbrecht** [GDquest/Blender-power-sequencer#406]
Hi, 
cross or gamma cross transition between Color Strips can be created. However, it is difficult to remove them again. Removing the cross or gamma cross strip via  "x or del" is not possible, the following error message occurs:
![Cross_fade_Color_Strips](https://user-images.githubusercontent.com/54477323/63639664-6990c480-c696-11e9-8de1-e6696ad315f3.png)

It is possible to remove the transtions strip via "Shft+x". In this case all strips right from the removed transition strip in the same channel will shift left by the amount of the duration of the removed strip.

[transitions_with_color_strips.zip](https://github.com/GDquest/Blender-power-sequencer/files/3537378/transitions_with_color_strips.zip)

Recommendation:
Don't allow transitions (cross or gamma cross) between Color Strips. 

By the way: It's great that power sequencer works with Blender 2.8 now!

**Comment by NathanLovato** [comment]
It's easy to fix this error. But why shouldn't we allow crossfades between color strips? They're visual strips like any others, if you want to fade from one color to another, fade from a video clip to white, etc., it's useful.
