### ISSUE TITLE
Cheat Sheet PDF

### ISSUE THREAD

**Issue by johnnygossdev** [GDQuest/blender-power-sequencer#412]
Hi! I'd like to put together a printable PDF that can be used to help me (and others!) learn the shortcuts.

Should I wait until 1.4? I know Nathan said there might be a lot of changes coming soon.

Cheers!

**Comment by NathanLovato** [comment]
We already have all the data in the add-on to generate it programmatically, e.g. we generate the docs from the source code: https://www.gdquest.com/blender/power-sequencer/docs/

A script to generate a cheat-sheet would be great, for example by filtering the info from the docs data.

What would you like to include, or what data would you need?

Each feature in the addon is converted to json with:

- A brief description
- A longer description
- A list of shortcuts and the corresponding action name

**Comment by NathanLovato** [comment]
I'm saying that because if the cheatsheet has shortcuts + the brief description for selected tools, it's easy to filter the JSON we use for the docs, so that we can update it automatically with each release.

**Comment by NathanLovato** [comment]
Note I'd also like to improve the theme for our generated docs on the website, but I could use a hand from someone who uses css more often than I do there

**Comment by jaggygames** [comment]
I think the shortcuts and the brief description would be enough.

I don't have much experience with using scripts but this sounds like the perfect opportunity to learn!

It would also be useful to learn for my own project which uses JSON so I'm down for giving it a go if you don't mind waiting a bit while I learn it :D

**Comment by NathanLovato** [comment]
Sure, if you can start to produce a list of what you'd like to have in the cheatsheet, I can help you with the python code, which will get you moving fast. Here are freshly generated shortcuts json to get you started:

[shortcuts_docs.zip](https://github.com/GDquest/Blender-power-sequencer/files/3563182/shortcuts_docs.zip)

Which operators would you like to have in your cheatsheet? You can see the id for each in the json, they're like `power_sequencer.*`

**Comment by jaggygames** [comment]
That's great thanks!

I'll first generate a pdf with all of them and perhaps have a section on most used for easy reference.

I'll play around with it and tidy things up a bit later as needed.

**Comment by NathanLovato** [comment]
Closing for now, as we have a cleaner reference and the getting started guide. You can reopen or comment if this is still relevant.
