### ISSUE TITLE
No progress bar shown when building proxies in 2.8

### ISSUE THREAD

**Issue by ChildishGiant** [GDquest/Blender-power-sequencer#413]
The tutorial shows a progress bar when building proxies but in 2.8 none is shown. However the icon on the windows task bar does have a progress bar and it is making the proxies correctly
Tutorial
![image](https://user-images.githubusercontent.com/13716824/64601736-67787680-d3b5-11e9-9601-6848a518a304.png)
2.8 (https://gfycat.com/dirtyquerulouslamprey)
![dirtyquerulouslamprey](https://thumbs.gfycat.com/DirtyQuerulousLamprey-size_restricted.gif)

**Comment by NathanLovato** [comment]
This has nothing to do with the addon, this is a blender feature/bug

**Comment by ChildishGiant** [comment]
Yea, sorry about that. It appears to be fixed in 2.81 anyway
