### ISSUE TITLE
Mouse trim behaves differently depending on shortcuts used

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/blender-power-sequencer#415]
In the docs it says that they should trim a selection (I'm thinking of a selection of strips cause otherwise I have no idea what we're talking about). But it behaves like this:

<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>RMB</kbd> - trims only the strip under mouse even if multiple strips are selected
<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Shift</kbd><kbd>RMB</kbd> - trims all strips no matter of how many strips are selected

This is inconsistent behavior, they should both either trim the strip under mouse, or the selection of strips or all strips, but not mixed depending on the shortcuts used.

**Comment by NathanLovato** [comment]
These are different tools. The first is a "quick trim and remove gap" tool, while the second is "trim to surrounding cuts". They're both essential time saving tools, that's why they're on mouse action, and there are few options for that. Blender already has builtin shortcuts that rely on almost all other mouse + modifier combinations.

Any suggestions for shortcuts? They should be feasible comfortably and fast with only 1 hand on the keyboard

**Comment by razcore-art** [comment]
Then it means it's a problem with the docs, because it gives you the impression that this is one tool that should behave consistently:
![image](https://user-images.githubusercontent.com/1177508/65379159-445e9880-dccc-11e9-9a5c-8f6412dcb5f3.png)

I'm going under the assumption that the docs are up to date.

I don't have a shortcut suggestion right now, but if I think of any as I edit I'll let you know.

**Comment by Kbex1** [comment]
It seem that Ctrl + LMB to select and cut does not work properly in 2.8 i see not purple border in-order to cut like in your video demonstrations on YouTube.

**Comment by NathanLovato** [comment]
@Kbex1 the [features reference](https://www.gdquest.com/docs/documentation/power-sequencer/reference/) for the tools is generated from the source code. You can change the documentation for a tool by modifying the text in """ """ in one of the files in operators/*.py files: https://github.com/GDQuest/blender-power-sequencer/tree/master/operators

![Screenshot from 2020-02-01 17-54-39](https://user-images.githubusercontent.com/12694995/73600838-f7ad8880-451b-11ea-92bf-e350d018b399.png)

Other guides, like [Getting Started with Power Sequencer](https://www.gdquest.com/docs/documentation/power-sequencer/getting-started/), are open to contributions, they're markdown files on our website: https://github.com/GDQuest/website/tree/master/content/docs/documentation/power-sequencer/getting-started

I updated the reference some time ago, closing this for now.
