### ISSUE TITLE
Apply Proxy to all strips

### ISSUE THREAD

**Issue by Kbex1** [GDquest/Blender-power-sequencer#417]
After you are import all your clips to Blender (and generated all the Proxies with BPSproxy) 
there is not way in blender currently to apply a proxy to all strips with a custom directory.
it can be an awesome addition to Power Sequencer

something like : 
[found on stackexchange and modified a bit](https://blender.stackexchange.com/questions/13977/apply-a-strip-property-to-multiple-strips)

```
import bpy

for s in bpy.context.scene.sequence_editor.sequences:
    if s.type != 'SOUND':
        s.use_proxy = True
        s.proxy.build_25 = True
        s.proxy.build_50 = True
        s.proxy.build_75 = True
        s.proxy.build_100 = False
        s.proxy.use_overwrite = False 
        s.proxy.use_proxy_custom_directory = True
        s.proxy.directory = bpy.path.abspath("//BL_proxy/") 
```
where proxy.directory is accessible through the add-on preference maybe ?

**Comment by NathanLovato** [comment]
I only support default proxy creation for now, yes. I'd need to know the problems you need to solve rather than direct feature suggestions.

You'd like to have all proxies from all projects in one central location? Or in one directory per project? And what's the purpose? Is it to make it easier to delete the proxies?

**Comment by NathanLovato** [comment]
It's important because it's not as easy as you'd think to make BPSProxy work that way. We need the default proxy location to check which files have to be re-generated more or less reliably.

**Comment by Kbex1** [comment]
the problem i faced is that after running BPSproxy for all my footage creating the proxies (outside of blender) and importing the original footage there is not easy way to apply that proxy in blender except manually selecting in the "Strip Proxy & Timecode" panel the directory and proxy resolution per each strip which is tedious. that's why i used that script to apply the proxies per all strips automatically.

**Comment by NathanLovato** [comment]
Ah okay so I didn't get your request. Well, this feature is already in blender: press A to select all strips, then call `Set selected strips proxy` from the `F3` menu or from the Properties panel.

Also, if you use our Local Import Footage feature, it sets proxies automatically - you can set the proxy sizes you use in the addon's preferences.

**Comment by Kbex1** [comment]
ah, yes i see. and then you set the proxy dir for the whole project.
i completely missed it. i will close the issue :)
