### ISSUE TITLE
Strips Proportional Speed Factor

### ISSUE THREAD

**Issue by Okanegahoshi** [GDQuest/blender-power-sequencer#418]
I don't know if it's appropriate, but I want to make a feature request here.
I want to be able to stretch the strip, while the strip always contain the same amount of video.

For now, to fit the strip into certain area, I "Add -> Strip Effects -> Speed Control", uncheck "Stretch to input strip length", calculate "Strip Length/Target Length" and put the result into "Speed Factor", and cut the strip to get rid of frames beyond the Target Length.
This is a tedious way to adjust the length of a cut clip.
(Right now "Stretch to input strip length" would try to play the whole timeline even after cut.)

So what I want is a way to automatically keep the beginning and the end of the strip while changing the length.
When stretch to half, play it twice faster; when stretch to twice, play it half.
If the strip is 120 frames, it always try to play that 120 frames of image no matter how long it is in the timeline.

This "Proportional Stretch" can be a mode to toggle in Speed Control Effect, or activated if ctrl or alt is hold before perform the stretch click.
Is this idea possible?
Any comment is appreciated.

**Comment by NathanLovato** [comment]
Yes, that's how the speed strip itself should work. I already tried to do something like that but it's not possible without a big hack and a lot of code to maintain. The speed strip itself needs to be fixed or improved in blender.
