### ISSUE TITLE
Crossfade fails with Color strips

### ISSUE THREAD

**Issue by davesb** [GDQuest/blender-power-sequencer#421]
Place a video strip followed by a color strip and try to add a crossfade;

Traceback (most recent call last):
  File "C:\Users\Dave Sunerton-Burl\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\Blender-power-sequencer\operators\crossfade_add.py", line 53, in execute
    s_to_offset = s_next if s_next.type not in SequenceTypes.EFFECT else s_next.input_1
AttributeError: 'NoneType' object has no attribute 'type'

location: <unknown location>:-1

Blender 2.81a

**Comment by NathanLovato** [comment]
Ah, this was already fixed. I guess you're using the version bundled with Blender. The bug should be fixed in the next Blender release. In the meantime, to access the bleeding-edge version, you can download this repository as a zip and install the addon from Blender's preference window.
