### ISSUE TITLE
Invalid syntax while enabling addon

### ISSUE THREAD

**Issue by anoopkeni** [GDQuest/blender-power-sequencer#429]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
When the enable check box is clicked, I get following error message.

`
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blender-power-sequencer-master\__init__.py", line 52
    addon_keymaps: List[Type] = []
                 ^
SyntaxError: invalid syntax

`

**What is the expected behavior?**
Addon works as expected.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. After installing the addon, in the Blender User Preferences window, select Sequencer
2. Expand the Sequencer:Power Sequencer
3. Click the checkbox.
4. A error message is displayed and the addon is not activated.

!-- 1. Click on the start button. -->

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by NathanLovato** [comment]
This is normal, since version... I think it was 1.2, you need Blender 2.80 at least. I'll add a note to the README right away.

**Comment by anoopkeni** [comment]
Ok There was no mention about it anywhere.

**Comment by NathanLovato** [comment]
I added the note to the README. You can use an older version of the addon with 2.79. This is the last version that should be compatible with it: https://github.com/GDQuest/blender-power-sequencer/releases/tag/1.2.0

Note that while it works, new bug fixes and features only are for the latest release, that is for Blender 2.80+

**Comment by anoopkeni** [comment]
This is a great help thankyou.

Blender 2.8 isnt working for me due to OpenGL requirement, even though I have 2nd Gen i7 with Graphics. Hope this will keep me going.
