### ISSUE TITLE
Error when enabling PS

### ISSUE THREAD

**Issue by tin2tin** [GDQuest/blender-power-sequencer#439]
Error when enabling PS:
![image](https://user-images.githubusercontent.com/1322593/97095660-a376a580-1662-11eb-8a86-868443413ccc.png)

**Comment by NathanLovato** [comment]
Thanks for letting me know. I'm not getting any error here in Blender 2.90.1.

Did you have the error with the version that's included in Blender or with the latest master branch from this repository?

**Comment by NathanLovato** [comment]
Also, could you confirm you only have one version of the add-on installed. Either the built-in one or the one from this repo? The error suggests it could be you are activating two copies of power sequencer; although I don't know how that could happen.

**Comment by NathanLovato** [comment]
Yeah, after purging this repo's version from my Blender 2.90.1 install, the version that ships in blender is working fine. I can't reproduce the error.

**Comment by tin2tin** [comment]
It might be related to disabling and enabling PS.

Btw. I'm working on a VSE workspace with a version of it where the PS functions are integrated into the existing menus.

**Comment by tin2tin** [comment]
This is the PS branch: https://github.com/tin2tin/blender_vse_reworked/tree/2.9
- not finished yet - there are a couple of functions I can't get working or I don't know if the are duplicates of the existing functions.

**Comment by NathanLovato** [comment]
I've tried that too and still can't reproduce the error. Are you using Blender 2.90.1?

> Btw. I'm working on a VSE workspace with a version of it where the PS functions are integrated into the existing menus.

Nice, thanks!

> there are a couple of functions I can't get working or I don't know if the are duplicates of the existing functions.

Yes, there are some operators that are meant to replace built-in ones, although they're under the power_sequencer namespace so they don't conflict with any of Blender's code.

**Comment by tin2tin** [comment]
I might have messed up along the way. 

One bug for sure is that the header is not restored after using your "blade" tool. The trim data keeps overwriting the menus, after switching to ex. select tool. 

A tweet with a gif of the integration - let me know if I messed something up: https://twitter.com/tintwotin/status/1320156304040775681
