### ISSUE TITLE
nvenc encoding 

### ISSUE THREAD

**Issue by mybestfriend3** [GDQuest/blender-power-sequencer#446]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Looks like nvenc encoding is not available on linux (blender 2.91) . Can't see any option or preset about this encoding.
NB: My local ffmpeg is nvenc capable. 
**What is the expected behavior?**

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by NathanLovato** [comment]
We only provide a preset to generate video proxies with a command-line program, bpsproxy. You can use your command line with a command like `bpsproxy -p nvenc` to use nvenc for transcoding.

Encoding in blender is unrelated to this add-on or your ffmpeg. Blender ships with a built-in version of ffmpeg that doesn't support nvenc.

Note that using nvenc over libx264 for encoding would barely improve rendering time, as the bottleneck is the sequencer's renderer, not encoding the frames with ffmpeg.
