### ISSUE TITLE
Channel offset with Down direction crashes Blender

### ISSUE THREAD

**Issue by RichardAntalik** [GDQuest/blender-power-sequencer#447]
**I'm submitting a...**
- [x] Bug report.
- [ ] Feature request.

## Bug report ##

Channel offset with Down direction crashes Blender if executed with strip in channel 1 selected

**What is the current behavior?**
Blender crashes

**What is the expected behavior?**
Blender not crashing, other than that not sure.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
[untitled.zip](https://github.com/GDQuest/blender-power-sequencer/files/5795417/untitled.zip)
Open file
Press Ctrl+Alt+Down arrow

**Other information** 
See https://developer.blender.org/T82942, why this is not bug in Blender

This should resolve crashing in this case.
```
diff --git a/operators/utils/functions.py b/operators/utils/functions.py
index b7d29dc..f24ca48 100644
--- a/operators/utils/functions.py
+++ b/operators/utils/functions.py
@@ -321,10 +321,9 @@ def delete_strips(to_delete):
     """
     if not to_delete:
         return
-    bpy.ops.sequencer.select_all(action="DESELECT")
+    sequences = bpy.context.sequences
     for s in to_delete:
-        s.select = True
-    bpy.ops.sequencer.delete()
+        sequences.remove(s)
```

**Comment by NathanLovato** [comment]
Thanks Richard, I'm marking it to fix today, along with merging the waiting PR, and I'll update the add-on in Blender.

**Comment by NathanLovato** [comment]
This is happening in the master build of Blender only, right? In 2.83 and 2.9 I can't reproduce it.

Anyway, using `remove()` is more readable, so all good.
