### ISSUE TITLE
Tool for checking shortcut assignments

### ISSUE THREAD

**Issue by tin2tin** [GDQuest/blender-power-sequencer#448]
I came across this script, which produces a svg with the shortcut written on it, so it is possible to quickly see shortcut assignments: https://code.it4i.cz/blender/blender-addons-contrib/-/blob/26a8b2eadc7abb2a30fac50eb5505aa24daf5785/system_keyboard_svg.py

Here are the default and the PS shortcuts enabled:
[keyboard_SEQUENCE_EDITOR_POWER_SEQUENCER.pdf](https://github.com/GDQuest/blender-power-sequencer/files/5926967/keyboard_SEQUENCE_EDITOR_POWER_SEQUENCER.pdf)

**Comment by NathanLovato** [comment]
Thanks for letting me know.
