### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Metaph413** [GDQuest/blender-power-sequencer#449]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

Traceback error whenever I attempt to mark the checkbox in the add on settings of Blender 2.91.2.

**What is the current behavior?**

Whenever I try to enable the add on, I get this error.

Traceback (most recent call last):
  File "(blender location)/2.91/scripts/modules/addon_utils.py", line 351, in enable
   mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender-power-sequencer-2'

**What is the expected behavior?**

To be able to use the add on without this.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

Go to Add-ons
Try to activate it.

## Other ##

**Other information** 

The Power Sequencer was not included in the version of Blender 2.91.2 I downloaded from the website, and I am trying to activate it using the Github download. Is there a reason for this on your end?

**Comment by NathanLovato** [comment]
>  ModuleNotFoundError: No module named 'blender-power-sequencer-2'

Did you name the extracted directory from github `blender-power-sequencer-2` ?

I'll check the latest Blender release. I didn't get any bug report or message that it was removed from 2.91.2. I'm seeing it's still in the official add-ons repository so it should be bundled automatically.

**Comment by NathanLovato** [comment]
I just downloaded blender 2.91.2 and I can see power sequencer bundled in there, activate and use it.

![Screenshot from 2021-02-08 18-13-23](https://user-images.githubusercontent.com/12694995/107297625-5d8af500-6a39-11eb-8fd7-4f876dcb6394.png)

**Comment by NathanLovato** [comment]
Also I can activate the development version no problem. You can try to name the folder in your blender addons folder exactly `blender_power_sequencer`, and please let me know if it helps.

**Comment by Metaph413** [comment]
> Also I can activate the development version no problem. You can try to name the folder in your blender addons folder exactly `blender_power_sequencer`, and please let me know if it helps.

That solution worked. You might want to let people know of this somehow.

**Comment by Metaph413** [comment]
I think the reason why the Sequencer didn't appear in the default Add-on list was because I accidentally deleted it somehow. I can't remember for sure.
