### ISSUE TITLE
Confusing versioning

### ISSUE THREAD

**Issue by paperbenni** [GDQuest/blender-power-sequencer#450]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Versioning is unclear

**What is the expected behavior?**
Not sure

The version that comes included with blender has the version number 1.5.1 that according to github releases doesn't exist. 2.93 doesn't ship with 2.0 either. The confusing part is that the actual 2.0 release from github displays 1.5.0 as its version number inside blender and has blender 2.81 as its blender version. It's unclear which version is actually newer and either one or the other has the wrong version number. I would submit a PR but at this point I'm not sure what the correct versioning is. 

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
Open blender, go to preferences-->addons-->power sequencer, look at version number

![20210305120308](https://user-images.githubusercontent.com/15818888/110108007-ee8c8c00-7dab-11eb-88b8-14128c987b89.png)

**Comment by NathanLovato** [comment]
Thanks, I had forgotten about this bit of code.

Just fixed it in 013efb2c30067f8903a70891e59c90790f8592a1
