### ISSUE TITLE
Remove align audio from documentation (re-generate documentation)

### ISSUE THREAD

**Issue by rainerschoe** [GDQuest/blender-power-sequencer#453]
## Bug report ##
The documentation mentions "Align Audio":
https://www.gdquest.com/docs/power-sequencer/reference/

however after ~1h of searching and browsing the code, I think this feature is not part of blender-power-sequencer.
I now found #441 which also confirms my guess :)

Maybe it is a good idea to update the documentation, or even better, put Align Audio feature back in, as it would be quite useful :)

**Comment by NathanLovato** [comment]
TODO; regenerate the docs as part of the build release script.
