### ISSUE TITLE
Update version in Blender

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/blender-power-sequencer#467]
After clearing remaining bugs. Also update README as people shouldn't use this repo anymore.

**Comment by Kreijstal** [comment]
why not?

**Comment by NathanLovato** [comment]
Workload and usability. You can't have two addons with the same name in Blender, this causes issues and confusion for users, as in #464. There should be a single version of the addon and it's best if it's the one included by default

**Comment by NathanLovato** [comment]
Done, v2.0.2 will be in Blender 3.3 LTS
