### ISSUE TITLE
Inform the docs.blender.org web team of the correct documentation links

### ISSUE THREAD

**Issue by rajeshduggal** [GDQuest/blender-power-sequencer#473]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
https://docs.blender.org/manual/en/latest/addons/sequencer/power_sequencer.html
The links to "getting started" and "Reference" are broken.

**What is the expected behavior?**
The user should be able to navigate to the correct web pages.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

Visit https://docs.blender.org/manual/en/latest/addons/sequencer/power_sequencer.html 
And click the getting started, and the reference links.

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by NathanLovato** [comment]
Thank you for pointing this out. That was missing redirects on the website. Fixed with https://github.com/GDQuest/website/commit/6c43a227e4e492ac38c58a799c864bf50badb3fd
