### ISSUE TITLE
Write cli tool to check and transcode videos to the same framerate

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#48]
To do:
- [ ] Read the framerate with ffmpeg
- [ ] Re-encode videos that have the wrong framerate

A very important tool as you'll find videos with 23.98, 24, 30, etc. fps online and Blender always treats them like they have the same framerate as your project. 

## Possible solution

From the command line:

- Check that ffmpeg and/or ffprobe are available. If not, warn the user and exit the program
- From Python, use ffprobe or another tool to check the framerate and info of every strip in a folder.
- Store a list of video file paths with info dictionaries (only framerate to start with)
- Build a list of the different video framerates found
- Either use a default framerate to transcode if it's set or let the user pick one valid framerate from a list
- Transcode the videos with ffmpeg and the `-r` option. Be sure to use `ntsc` and other built-in keywords for non-integer rates (not `29.98` etc.).

Feel free to ask help with the ffmpeg commands!

## Extra notes

If you know a standard python lib that does it or a lightweight cross-platform python 3 script/lib/module we can ship with the add-on, great, we could avoid the external dependency. The lib's license **must be compatible with the GPL license Blender uses**.
Otherwise FFprobe comes with ffmpeg, which is almost necessary if you do FOSS video editing.

**Comment by NathanLovato** [comment]
Refs

https://askubuntu.com/questions/110264/how-to-find-frames-per-second-of-any-video-file

ffprobe can output json
https://stackoverflow.com/questions/42023222/python-program-which-reads-and-extracts-specific-information-from-json-file-gene

You can read it from ffmpeg too, gotta see if it's the value we need? but as blender uses ffmpeg I'd assume it's what it uses, had the issue a few time where fps and tbr values were different and blender used the fps
https://stackoverflow.com/questions/9896644/getting-ffprobe-information-with-python

**Comment by NathanLovato** [comment]
Maybe merge with build_ffmpeg_proxies and turn it into a cli interface to make use of #62 / needs object orientation in this case to keep the code easy to read and write

**Comment by doakey3** [comment]
I think I've got one started. See [this commit](https://github.com/GDquest/Blender-power-sequencer/commit/c6d131771f30f03c92f4bddd90526a04ac567914).

**Comment by NathanLovato** [comment]
So cool! ^^

**Comment by NathanLovato** [comment]
Closing as now I consider this beyond the scope of the add-on, that should focus on video editing operations (cut, trim, offset, etc.). A tool like this is much more easily done with shell script too.
