### ISSUE TITLE
[DOCS] Add "import local footage"

### ISSUE THREAD

**Issue by davcri** [GDquest/Blender-power-sequencer#51]
Here it is!  
Let me know if there is something, in either form or content, that can be improved!

*EDIT*: changed "Blender root folder" to "Blender project folder".

---

# Import local footage
**Description**: imports all images from a folder named `IMG`.

**How to use it**: 
1. Create a folder named `IMG` inside your Blender project folder (where the *.blend* file is)
2. Put images inside this folder
3. Go in Blender sequencer:
   1. Press <kbd>SPACE</kbd>
   2. Type `ps importer`
   3. Press <kbd>ENTER</kbd>

*Note*: Blender project needs to be saved before using this feature.  

![import_local_footage](https://user-images.githubusercontent.com/6860637/33723999-76c86a46-db6e-11e7-83b2-499d4164235b.gif)

Images will be stretched, by default, to fit the entire screen; if you want to keep the original size, read the next section.

**Comment by NathanLovato** [comment]
Actually it imports more than this. Doing a video for it in a moment, after I'm done with the accounting.
You can also have `video` and `audio` folders in which it'll look for, well, video and audio.
If you use the keymap that ships with the add-on you can press `Ctrl Shift I` at the moment.

**Comment by davcri** [comment]
> Actually it imports more than this.

My fault, I totally forgot about video and audio import! Tomorrow I'll work on completing this doc.

**Comment by davcri** [comment]
New one: 

---

# Import local footage
**Description**: imports all images, videos and audios from folders
named respectively: `IMG`, `VIDEO` and `AUDIO`.

**How to use it**:
1. Create folders `IMG`, `VIDEO` and `AUDIO` inside your Blender project folder
(where the *.blend* file is)
2. Put resources in the appropriate folder
3. Open your project in Blender, open the sequencer then:
   1. Press <kbd>SPACE</kbd>
   2. Type `ps importer`
   3. Press <kbd>ENTER</kbd>

*Note*: Blender project needs to be saved before using this feature.  

![import-local-footage](https://user-images.githubusercontent.com/6860637/33778159-c52065c0-dc47-11e7-9d66-3f0b7037b959.gif)

Images will be stretched, by default, to fit the entire screen; if you want to
keep the original size, read the next section.

**Comment by NathanLovato** [comment]
Thank you very much! The GIF is excellent. I just edited your post to give you a sense for writing suggestions:

- No need to write `description` at the top
- The picture is excellent, best if it's at the top - with other tools the picture alone might better convey what the tool does than the list
- Let's use h2 `##` for the first title and h3 `###` for sub-sections like "How to use", "Options", "Tricks" and everything we might add later. The reason to start with H2: we'll probably have multiple tools on one page. E.g. I'd group all import/export features in one place.
- The short bottom extra note is self-explanatory
- Let's avoid passive voice when possible (is used, are processed, etc. -> XX uses, XX processes). There was one in your example.

On top of that, if you're going to spend time helping me, we should set a repo to store the docs so you can upload your changes directly. What do you think?

*I'm not sure about how to handle each tool's options, when you press F6 after you called the operator. For now we can leave them out but I've looked into possible solutions to automate the extraction of docstrings/descriptions from python. There's the built-in pydoc module for instance, but you'd need a custom solution to extract the description of Blender properties. In any no one should copy them by hand. Anyway it's not a priority for now.*

**Comment by davcri** [comment]
Ok I wrote down your tips on the docs repo (https://github.com/GDquest/Blender-power-sequencer-docs), so also others can read them. 

For the actual documentation, I created a `docs` folder in the same repo.

> [...] In any no one should copy them by hand. Anyway it's not a priority for now.

I agree on that one, when the docs about the main 5 features are completed I'll think about something.

**Comment by NathanLovato** [comment]
Closing all docs issues, let's open new tasks in https://github.com/GDquest/Blender-power-sequencer-docs/
