### ISSUE TITLE
Update to Blender 2.79

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#53]
Most of the add-on should still work, aside from the quick export function ( see #40 ). But gotta review api changes and go through the functions to see if anything else broke.

**Comment by NathanLovato** [comment]
@davcri by any chance are you using Blender 2.79? If so any bugs so far?

**Comment by davcri** [comment]
Yes,  I use Blender 2.79 from when it was updated on the Arch Linux repository (2017-08-08:  https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/blender).

No bugs till now, but I didn't tested all the features.

**Comment by NathanLovato** [comment]
Seems okay so far, no new bugs found :)
