### ISSUE TITLE
build_ffmpeg_proxies: auto-detect proxies to (not) build

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#62]
UPDATE: 
The default location for proxies in Blender is:

- you get a BL_proxy folder that contains proxies next to your media
- Video proxies end in `BL_proxy/%filename%/proxy_%size (25, 50, or 100)%.AVI`: one folder for each video, with the same name as the original video file.
- Picture proxies are in `BL_proxy/images/%size (25, 50, or 100)%/%filename%

To detect new proxies that need to be built it's easy enough: you can check for missing paths.
For now we rarely need to update proxies as you're not going to change recorded footage... so I've updated the task to reflect that need.

**Comment by NathanLovato** [comment]
Work started on the ffmpeg-build-script branch. First refactoring and breaking down the script then I'll add the timestamps etc.

Where would you save the timestamps and build data? Inside each BL_proxy folder?

**Comment by sudopluto** [comment]
i think we can break this up to two parts:
- 1) sort of static monitoring of file changes
- 2) the sort of watchdog service that is popular in web dev servers

**Comment by NathanLovato** [comment]
Watching would be nice, but yeah first things first: that would be for another task. I think it'd be best to integrate it as a Blender operator and connecting it to the built-in progress bar before adding something like watch.

**Comment by NathanLovato** [comment]
Can you take care of it @razcore-art ? I don't want BPSProxies to have support for all proxy options in Blender as it would make it impossible to use the tool outside of Blender and be more code to maintain.

The default location for proxies in Blender is:

- you get a BL_proxy folder that contains proxies next to your media
- Video proxies end in `BL_proxy/%filename%/proxy_%size (25, 50, or 100)%.AVI`: one folder for each video, with the same name as the original video file.
- Picture proxies are in `BL_proxy/images/%size (25, 50, or 100)%/%filename%

To detect new proxies that need to be built it's easy enough: you can check for missing paths.
For now we rarely need to update proxies as you're not going to change recorded footage... so I've updated the task to reflect that need.

**Comment by razcore-art** [comment]
I'll close this and open up an issue to keep track of stuff to improve at the [BPSProxy](https://gitlab.com/razcore/bpsproxy) new repo
