### ISSUE TITLE
Add feedback for  "Render video for the web" 

### ISSUE THREAD

**Issue by davcri** [GDquest/Blender-power-sequencer#77]
I used the "Render video for the web" operator, but it seemed like it didn't work because I didn't receive any feedback. I think the only way to receive feedback is to have the property editor open. 

Is it possible to add some kind of feedback? For example: 
> *Rendering options changed*

With the *auto render* option set to true this is not a problem, but I think that this option is defaulted to false.

**Comment by NathanLovato** [comment]
Done!
