### ISSUE TITLE
blender-power-sequencer-1.0-beta-keymap...

### ISSUE THREAD

**Issue by cvazx** [GDquest/Blender-power-sequencer#80]
is not recognized by Blender 2.79 Linux, or the 'alpha' version.

Also the new beta version is missing it's 'blender-power-sequencer' container folder/dossier in the zip. I created one and placed the contents in it, now it's available to Blender in the add-ons.

Thanks for all your great work (including with Krita)...
Cheers !

**Comment by NathanLovato** [comment]
I just added the zip. For the keymap it's weird. Did you try importing it via the preferences window? It's a pure python script exported by Blender. @davcri I think you didn't have trouble using the keymap file?

**Comment by davcri** [comment]
No problem with keymap file here! I also tested the new [1.0 Beta](https://github.com/GDquest/Blender-power-sequencer/releases/tag/0.9.0) with keymap.

@cvazx you can try to momentarily delete the Blender configuration and re-install the add-on:

1. Rename the config folder to a different name:
```sh
mv ~/.config/blender/2.79 ~/.config/blender/2.79-BKP
```
2. Install the add-on

**Comment by cvazx** [comment]
Thank you both. 
On the 'Input tab' at the top, reading from left to right... I was expecting to find the keymap under the 'Presets' pulldown, when in fact it was in the pulldown just to the left of 'Presets'. All good now, all functions available. Will be giving it a spin in short order. 

Again, thanks for the help! 

(et café) :^D

**Comment by NathanLovato** [comment]
Ah yes it doesn't switch automatically to the newly imported keymap. #81 should remedy that.
