### ISSUE TITLE
Keymap: Ctrl Shift R-Click for trim collides with Select linked

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#85]

**Comment by NathanLovato** [comment]
See #91
Another issue: Alt Select mouse selects neighboring handles so moving it to Alt may not be best either

**Comment by doakey3** [comment]
Is this still an issue? I can select linked with the L-Key and Ctrl+Shift+RMB seems to trim ok.

**Comment by NathanLovato** [comment]
Select linked is an option on select mouse. By default if two strips have the same duration and they're aligned, Ctrl right click and Ctrl shift right click will select both at the same time. Trim strips overrides that. Adding alt to the shortcuts

**Comment by NathanLovato** [comment]
closed with https://github.com/GDquest/Blender-power-sequencer/commit/1dd634add738688b38c5811a53af609d423e38aa
