### ISSUE TITLE
Add a 'Specials Menu' at mouse cursor?

### ISSUE THREAD

**Issue by tin2tin** [GDquest/Blender-power-sequencer#88]
Really impressive work! However, I fear that users might get lost without any UI element to learn all the functions and shortcuts from. Since many functions relate to mouse cursor position, buttons may not be such a good idea, but have you considered a sequencer case-sensitive 'Specials' menu, like 'w'-menu in the 3D Viewport? I'm not much of a coder, but here's an example of a 'Specials' Menu for the Sequencer(Mouse cursor must in in Sequencer and hit 'w'). I hope that it may inspire you to make your script more user-friendly: 

```
import bpy

class SequencerEditMenu(bpy.types.Menu):
    bl_label = "Specials"
    bl_idname = "SEQUENCER_OT_sequencer_edit_menu"

    def draw(self, context):
     
        if context.space_data.type == 'SEQUENCE_EDITOR':

            layout = self.layout
            layout.operator("sequencer.gap_remove").all = False
            layout.operator("sequencer.gap_insert")
            layout.separator()
            props = layout.operator("sequencer.strip_jump", text="Jump to Previous Strip")
            props.next = False
            props.center = False
            props = layout.operator("sequencer.strip_jump", text="Jump to Next Strip")
            props.next = True
            props.center = False            
            layout.separator()            
            layout.operator("transform.transform", text="Grab/Move").mode = 'TRANSLATION'
            layout.operator("transform.transform", text="Grab/Extend from Frame").mode = 'TIME_EXTEND'
            layout.operator("sequencer.slip", text="Slip Strip Contents")            
            layout.separator()
            layout.operator("sequencer.cut", text="Cut (Hard) at frame").type = 'HARD'
            layout.operator("sequencer.cut", text="Cut (Soft) at frame").type='SOFT'         

addon_keymaps = []
def register():
    bpy.utils.register_class(SequencerEditMenu)

    # handle the keymap
    wm = bpy.context.window_manager
    kc = wm.keyconfigs.addon
    if kc:    
        km = wm.keyconfigs.addon.keymaps.new(name='Sequencer', space_type='SEQUENCE_EDITOR')
        kmi = km.keymap_items.new('wm.call_menu', 'W', 'PRESS')
        kmi.properties.name = "SEQUENCER_OT_sequencer_edit_menu"    
        addon_keymaps.append((km, kmi))

def unregister():
    bpy.utils.unregister_class(SequencerEditMenu)

    for km, kmi in addon_keymaps:
        km.keymap_items.remove(kmi)
    addon_keymaps.clear()
    
if __name__ == "__main__":
    register()
```

**Comment by NathanLovato** [comment]
There is a contextual menu already. It should be mapped to... Alt X? Its content changes based on your selection. It's a bit limited right now - it's has 5-6 options in total, but it's mostly that I wasn't sure what to put in there and how to structure it for good UX: the more options you add, the less clear it becomes. 

Now there are tabs in the properties panel, it should be worth adding a dedicated one for Power Sequencer too.

In the meantime, this should be in the docs: you can press `Spacebar PS.` to find all available tools with their shortcuts. Gonna open two UI tasks, thanks.

**Comment by tin2tin** [comment]
Oh, I did not know that. Maybe also use the 'w' shortcut key for that contextual menu so it will be consistent with the rest of the Blender areas?

**Comment by NathanLovato** [comment]
Read about the specials menu, and it seems like a good pick. Changing it now, thanks for the feedback :)
