### ISSUE TITLE
UX: Design a Menu/Panel for Power Sequencer

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#90]
Work started already, look below

![blender_2018-08-01_13-10-35](https://user-images.githubusercontent.com/12694995/43500701-e3585b52-958c-11e8-8e42-da1906ba928b.png)

**Comment by doakey3** [comment]
I noticed that the bl_label for most of the operations starts with "PS."

This makes it easy to search for all the operations associated with the addon in the spacebar menu, but if I add these to the panel, the buttons that activate these operators will all have "PS." on them, which will look a little ugly/redundant.

My vote is to remove the PS. from the operator bl_labels so our panel will look nice.

**Comment by NathanLovato** [comment]
Yup, if we have some UI, it's time to remove that.

**Comment by NathanLovato** [comment]
Done!

**Comment by aditiapratama** [comment]
Hello I'd like to contribute for this issue.

**Comment by NathanLovato** [comment]
We had some UI but I just noticed it's gone. I only use shortcuts so I didn't notice 😅
@doakey3 did you remove it? Gonna restore the files now.

No, there's no design at the moment. This task is also about designing the menu. I use keyboard shortcuts and the spacebar all the time so I don't know what people would need the most. I'll share a message on Twitter to see if someone wants to help

**Comment by NathanLovato** [comment]
Here's two screens of the current menus:

![blender_2018-08-01_13-10-35](https://user-images.githubusercontent.com/12694995/43500701-e3585b52-958c-11e8-8e42-da1906ba928b.png)
![blender_2018-08-01_13-12-22](https://user-images.githubusercontent.com/12694995/43500705-e4d37c28-958c-11e8-85f1-3c8679172c84.png)

**Comment by doakey3** [comment]
I was trying to make a sort of categorical menu, but I didn't really put too much effort into it because I also use the keyboard shortcuts exclusively. I ended up removing the code prior to the v1.0 release.

![untitled](https://user-images.githubusercontent.com/16495887/43500850-16915b88-9518-11e8-8962-7470419919fb.gif)

That said, it would be nice to have a quick way to change some of the properties (how long fade-outs should be, how much speed to add when using the add_speed operator, etc). I'll be interested in seeing what you come up with.

I had a copy of an old working dev version of the addon that had the UI shown above still implemented. You can download it below: 

[Blender-power-sequencer-dev.zip](https://github.com/GDquest/Blender-power-sequencer/files/2248014/Blender-power-sequencer-dev.zip)

**Comment by lucianomunoz** [comment]
Hey what about we treat the strips as objects, so we can have their properties in the properties panel, modifiers, in the modifiers and decluter the N panel?
I've been thinking about doing some mockups of this for a while just havent had the time.
Also I would separate the effects strips into two at least, the ones that affect or need a strip as a base (i.e. speed control), and the ones that can work on their own (i.e. color)

**Comment by NathanLovato** [comment]
@lucianomunoz I think there's a misunderstanding on the issue, the goal is to create some menu for PS. There's no other place to put that interface in the sequence editor - but we're already using a tab separate from the properties and modifiers.

> having a T panel for the vse

This sounds like a job for Blender, not for a python add-on. We can't modify the native UI without hacky code or adding manual steps to install and update the addon (replace UI files in your blender install)

**Comment by 3pointedit** [comment]
This has always been an issue with the VSE. most solutions have been simply
to clutter the bottom bar with buttons. Is a floating tool menu out of the
question?

**Comment by NathanLovato** [comment]
The floating menu already exists: https://github.com/GDquest/Blender-power-sequencer/issues/89
Another option is pie menus, where you can have multiple floating panels and subcategories - but there again, need someone to do UX design

**Comment by 3pointedit** [comment]
Would you get good feedback on rightclick select website?

**Comment by aditiapratama** [comment]
I was thinking to implement Pie Menus, but I guess better to make another issue and reference it.

I don't know if this good idea, but by put it in standard menu might help the user to find this addon at the first glance

![image](https://user-images.githubusercontent.com/982553/44074362-77a8c316-9fc2-11e8-9c83-3d9d1f77a26f.png)

**Comment by 3pointedit** [comment]
Tool discoverability is a real problem for blender in general and the vse
particularly as it does not have context or modal tools

**Comment by NathanLovato** [comment]
> Would you get good feedback on rightclick select website?

It's not a place to ask for feedback for add-ons, it's only about suggesting/discussing changes to blender itself.

> I was thinking to implement Pie Menus, but I guess better to make another issue and reference it.

Yeah definitely! I'm preparing a 1.1 release video, and I'll ask for people to come help with UX, to help you with these issues.

> I don't know if this good idea, but by put it in standard menu might help the user to find this addon at the first glance

Yes, good idea 🙂

**Comment by NathanLovato** [comment]
We have a menu in the toolbar that's pretty complete, nothing to put in the panel, so I removed it, and we can now close this
