### ISSUE TITLE
Mouse cut and trim: ignore locked strips

### ISSUE THREAD

**Issue by brousselle** [GDquest/Blender-power-sequencer#94]
I want to edit my video in sync with a background music. (for instance)
Let's say my background music is locked.
So i would like to be able to:
- cut all strips except the locked one in a single click
- cut gaps a created while trimming strips even if there is a locked strip in the way.

PS: this addon is awesome :D

**Comment by NathanLovato** [comment]
Done!

**Comment by brousselle** [comment]
![capture](https://user-images.githubusercontent.com/4159047/34609661-d77a276a-f21d-11e7-8762-aa93058473ad.jpg)
Works like a charm :+1: Thanks for the quick fix.
But i still miss cutting gaps like in the screenshot provided when i click Ctrl+Lmouse on the cursor.

**Comment by NathanLovato** [comment]
That's much trickier to add - Blender itself doesn't support this natively. Put all your strips except the locked one in a meta strip, enter and you can edit to the music no problem

**Comment by NathanLovato** [comment]
Another option is to use Ctrl Alt Right to select everything after the cursor, G and drag to the left to move everything back.

**Comment by brousselle** [comment]
Well it does work, but this is useless as i cannot hear and see the waveform of the music while i edit the video.
My point, and i guess some other people will want to do this also is to sync cuts in the video with the waveform of the music.
I also found that trimming the video with the fix you proposed does not work neither.
So i guess this will be more complex than expected, but for me the addon is almost useless if i cannot leave the music unmodified :(

**Comment by NathanLovato** [comment]
```
i guess this will be more complex than expected
```
Everything that blender doesn't support needs to be coded from scratch. Means hours of benevolent work to write but more importantly to maintain it. If people give a hand it can happen but not alone.

Did you upgrade to the latest master? Here trimming one or multiple strips works with the lock. It seems the fix broke the remove gap feature though.

**Comment by brousselle** [comment]
i fully understand what you mean ;) i wrote a few pythons functions to help my daily tasks on blender sequencer... but i code like crap, and your approach looks much better ;)
I need to go into the code to see if i can contribute.
Thanks for starting this project and share it with everyone ;)

I upgraded to latest master and got this error message while trimming
https://pastebin.com/xHH7V8cj

I will leave soon, so won't be able to test further before next week.
May be this is a good oportunity for me to dig into the code to see if i can find the problem.

**Comment by NathanLovato** [comment]
Please update to the latest version, just restored remove gaps and cut gaps.
You can open an issue for the custom remove gaps and I can give you a hand to get it working. It'd be a good opportunity to make one that's relative to the mouse cursor or any frame you'd like (so it doesn't involve the time cursor every time).
