### ISSUE TITLE
Change trim mouse mode to channel mode

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#95]
When you ctrl click and drag on a strip, it only trims this strip. This is "mouse"mode: only affects what you initially clicked on. But now the trim is interactive, I feel like working with the entire channel may be more intuitive. Eventually we can add time cursor snapping or openGL preview of the cut + mouse snapping and remove the need for the time cursor to make sure you don't trim past the end of a strip?

**Comment by 3pointedit** [comment]
Do you mean a ripple trim? That is alter all of the media start frames to the right of the trim? Or do you mean to change the Offset of all of the other strips on the channel?

**Comment by NathanLovato** [comment]
Ah it's an old issue, the tool works well as it is now. The question was whether Ctrl Click and drag should let you trim past one strip's start/end frame or not. But after a few months working with it it's handy as it is now for audio and 3-point editing
