### ISSUE TITLE
1.0 release post

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Blender-power-sequencer#99]
Explain what the tool is about, cover all the essential features, how to download and get started, how to contribute

**Comment by doakey3** [comment]
Sounds like a pretty big project. I have an for how to get it done.

1. We separate the video into chapters, ie.
    - "This video has been updated, you can find a link to the current version in the description"
        + We can make this part of the video invisible until an update to the video is made
    - Intro (in 30 seconds, describe what the addon does)
    - Installation
    - Making/Installing a personalized keymap
    - From here, we could do a chapter about each operator
2. Upload these videos to a shared folder, perhaps on [the docs page](https://github.com/GDquest/Blender-power-sequencer-docs), but we might run into the [1GB cap](https://help.github.com/articles/what-is-my-disk-quota/).
3. Write a python script that uses ffmpeg to combine these clips into a single overview video.
    - Specify the render order of the videos
    - Combine separate .SRT files into one (if we have any)

The advantage to doing it this way is that we can separate the job into smaller parts. Also, in the future, when parts of this overview video become obsolete, we can re-record only the chapters that require updates.

What resolution & frame rate do you use for recording?

**Comment by NathanLovato** [comment]
This task is only for communication. As the title says, it's about giving an overview of the release.
For now complete video docs would be too much work to be worth it. It's not a huge huge job but users barely watch docs-like tuts (NB: I make tutorials for a living). I think your generated readme is really efficient and much faster to go through than a long video.

I had plans to do a complete Blender video editing training series that uses both vse transform and power seq. This should have some success. The scope would be larger though, and I have a backlog of what... 100 tutorials to make now? So it's not happening soon unfortunately ^^

Aside from that sure your idea for the process is good. A shared cloud folder should do the trick for something like this - git doesn't work between the lfs bandwidth limit you hit super fast (mine's locked after I let people dl videos on some repository) and yeah hitting the 1gb limit with pure git.

I tend to work at ntsc-film (23.97...). Fewer frames to encode and render this way. For screencast-like tuts 30fps doesn't add much.

**Comment by NathanLovato** [comment]
Just added a `tutorial` label for tuts-related issues.

**Comment by NathanLovato** [comment]
Annnnd.... done! https://github.com/GDquest/Blender-power-sequencer/releases/tag/1.0.0
